### ISSUE TITLE
KB3081424 Update After login screen failure

### ISSUE THREAD

**Issue by dsyo2008** [PFCKrutonium/Windows-10-Login-Background-Changer#101]
Hello, what time to repair the login screen settings?

**Comment by tetra-fox** [comment]
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
