### ISSUE TITLE
Issue after applying settings with new cummulative update installed

### ISSUE THREAD

**Issue by Shaggy410** [PFCKrutonium/Windows-10-Login-Background-Changer#102]
Hi.

I'm having some issues after I try to change the default logon screen when the cumulative update (KB3081424) has been installed on the system, this led to screen flickering at the lock screen resulting in inability to log onto the system, tried on other system with the same results, and it sometimes (1 out of 5 tries or so), let me type the password and log.

This is a video I took off the screen of one of the systems, showing the flickering at lock screen, this happened with latest version of the background changer.

https://www.youtube.com/watch?v=d1MCrSG7SL4

At the moment, the solution I found to being able to log back on the system, is get a recovery media, or W10 iso, and from CMD revert to pri.bak, obviously this will leave the system with the default logon background, but will grant access to the system.

Best regards.

Shaggy410

**Comment by nishantgupta107** [comment]
can you please elaborate how you reverted to pri.bak.
my friend is also facing the same problem

**Comment by trevorlloydelliott** [comment]
Same issue as above.  @PFCKrutonium please take down this repo until it is fixed with the latest Windows 10 update.  It has locked me out of my PC for the time being (can't even enter in safe mode).

**Comment by darth62969** [comment]
people we cannot help if you don't give us some more information.

please provide us with your specs so we can better understand what is going on.

**Comment by wbercx** [comment]
I had the same issue today. I found this tool just an hour ago, after having applied all the Windows updates earlier today, and ended up with a flickering, completely unusable login screen.

I'm on a Surface Pro 3, i5/256gb. The mouse would work, and if I pressed the power button the "Slide to shut down PC" screen did come dangling down from the top looking perfectly fine and not flickering at all. But I couldn't log in.

I managed to boot into recovery by bashing Shift + F8 as fast as I could just after powering on my Surface. It took me about 20 attempts, but finally managed to get into recovery. I attempted to restore a pre-Windows Update restore point, which it claimed had failed, but my login screen has returned to normal.

@darth62969 Don't know what else to tell you.

**Comment by Shaggy410** [comment]
Specs of the systems, take into consideration that both were clean installations:

This one is a Desktop PC:
Athlon 2 X2 260
16GB RAM
Windows 10 PRO, running on a RAID 0
AMD R9 290 graphics adapter

The other, is an Alienware m15x:
Core I7 Q740
6GB RAM
Windows 10 PRO, running on an SSD
Radeon HD 5870 graphics adapter

A thing to take into consideration, is that before the mentioned update, I had both systems with a different logon Background and everything was working fine, the issue started after both systems installed the update

As to how to revert to the bak pri:
- Boot onto your W10 iso and select Repair Computer
- Navigate to the Troubleshoot menu
- Go to Advanced Options
- Enter to the Command Prompt
- On the CMD go to the drive with your Windows instalation (mine was D, yours may vary, check with a dir command, if it shows your Windows, Users, and other systems folders, it's that one)
- Run the next commands on the CMD:

Cd C(or your drive letter, in my case was D:):\Windows\SystemResources\Windows.UI.Logon
Del Windows.UI.Logon.pri
Copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri
- Reboot your system, it should now let you log onto the system

**Comment by darth62969** [comment]
ok first think i notice after i update my desktop, the old windows 7 boot sound is back... WHY? second thing is that the logon screen reset. so what i think is they changed something with the Window.UI.Logon.pri file and that makes an update, necessary, if you really must have a different wallpaper either to restore your system then disable this update via command line or use the Transparent PNG option provided here. 

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/58

**Comment by BirkBorkason** [comment]
same problem here, cant login! asus f205t with KB3081424

**Comment by Shaggy410** [comment]
Tried again with version 1.0.2.0 with no success, PC gets on a loop at logon screen that renders it unusable, reverted to pri.bak via Linux

Tried to attach defective pri file, but couldn't...

**Comment by tetra-fox** [comment]
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by Shaggy410** [comment]
Followed steps stated on the Wiki, system keeps getting stuck on a logon loop, until an exception is thrown, then gets looped on exception.

![img_20150806_172517](https://cloud.githubusercontent.com/assets/13673072/9125688/4cfae6da-3c60-11e5-9c6a-dce1fad05bac.jpg)

**Comment by darth62969** [comment]
first strike witches, nice
make sure you have the latest version, i believe the latest and the last version are numbered 1.0.2.0, this is the symptom of the last version being used on the latest update to windows.

**Comment by Shaggy410** [comment]
Issue happened with the latest version.

Followed the steps on the wiki up to the log in one, after I managed to log into the system, went to the releases page and downloaded 1.0.2.0 as you mention.

Ran it, and after a reboot the symptoms were the same as before, with the difference of the exception being thrown by the system.

Might try to do a video with the steps I followed

**Comment by WiretapStudios** [comment]
So, I signed up just to chime in that the same thing happened to me. I'm locked out of my desktop (I'm on a laptop now), and didn't realize they had removed boot in safe mode for the upgrade to 10 (I was on 7 prior). So, any ideas how I can get back in?

 I tried creating a usb and also a disc from my laptop, but both came up with errors, so that might be a lost cause without a lot of work figuring out what's causing that to happen. 

So right now, I'm stuck with a desktop that goes to the login screen and flashes like a strobe light. I downloaded the most recent version, and it took me several hours just to find this thread about it.

**Comment by s0urcelab** [comment]
@WiretapStudios maybe you can create a UEFI PE on your U disk.
when you get into PE system,just find the .bak file and replace it！

**Comment by s0urcelab** [comment]
@Shaggy410 did you manage to change background without flash error by the lately version?

**Comment by WiretapStudios** [comment]
It was the latest version that caused the problem. And no, I can't do all
that because I have no idea what that entails. I've been talking on the
chat with the guy that made it, but he doesn't know how to fix it either.

**Comment by s0urcelab** [comment]
@WiretapStudios I have ISO of PE system.I'd like to provide it,but its chinese version.I'm not sure you can use it without any mistake.So now you still can't find a way to login into win10?

**Comment by Shaggy410** [comment]
@source2git As mentioned above, I was not able to change the background even when following the steps mentioned on the wiki and using the latest version (1.0.2.0), it ended on the log in screen looping, then throwing an exception, and looping back to only keep throwing the exception

@WiretapStudios Maybe you can try booting a live Linux Image (Ubuntu, Fedora, etc), and from the file manager of the Live System you can revert to the pri.bak

**Comment by WiretapStudios** [comment]
I just reinstalled, it ended up fixing it, thankfully I had a restore point
to go to I found when I was going through the reinstall menu from a usb
boot.

**Comment by zgrywek112** [comment]
Tried using cmd to overwrite the .pri file. Unfortunately, it seems like there is no .bak file in the folder. Any ideas on how to fix that?

**Comment by s0urcelab** [comment]
@zgrywek112 I upload my .pri file as a image(rename it as Windows.UI.Logon.pri),if that could help you~
![windows ui logon](https://cloud.githubusercontent.com/assets/13177782/9189881/76af53fc-4021-11e5-911f-53509e089cbe.jpg)
maybe this img looks like broken,dont worry,it definitely works,just download it~

**Comment by BringMeTheGaming** [comment]
My computer has the same problem.. I don't know how to do anything of what you guys have written

**Comment by BringMeTheGaming** [comment]
Any help?

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Comment by Shaggy410** [comment]
At the moment, it has worked correctly on the 2 pcs. Thanks
