### ISSUE TITLE
Complet crash using on multie desktop setup

### ISSUE THREAD

**Issue by sakoarts** [PFCKrutonium/Windows-10-Login-Background-Changer#103]
I used this app to change the logon screen on my laptop on which it worked perfectly. Now I tried it on my triple screen desktop, using a triple screen background image and setting image scaling on 1080p. And now my windows logon crashes completely. 
When windows startup reaches the point where it loads the logon screen, it starts the beginning of a loading animation, than turns black, than  starting the loading animation again, and repeating this infinitely 4 times a second. 
Appart form fixing this error in your app, I would like to solve this issue without resetting my complete installation (which I just finished). Things I tried that did not work: Startup repair, (sadly enough there were no restore points), Starting in Safemode, Setting AutoAdminLogon in registry via command prompt. Is there a way that I can reset the changed files via commandprompt?

**Comment by darth62969** [comment]
the lock screen is not designed to span 3 monitors, this something you would have to take up with microsoft

**Comment by tetra-fox** [comment]
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by sakoarts** [comment]
Thanks for your reply, I guess indeed the lockscreen itself is not compatible with multiple monitors.
I saw the added information on the wiki however it refers to interacting with a file called "W10 Logon BG Changer - Command Line.exe" However I cannot find this file within the source and it seems I connot interact with the standard compiled application. 
Where can I find this file?

**Comment by tetra-fox** [comment]
@sakoarts by read the wiki, I mean go to the "can't login" page since that is your problem

**Comment by sakoarts** [comment]
The instructions worked great, thanks!

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
