### ISSUE TITLE
Commandline version

### ISSUE THREAD

**Issue by ghost** [PFCKrutonium/Windows-10-Login-Background-Changer#104]
Program has worked flawlessly for both my laptop and desktop systems.

Would appreciate a pure commandline version so that it can be used with scripts and such

**Comment by tetra-fox** [comment]
There is one, but I broke it. Have been trying to fix for days now. Debugging hasn't given me any errors so I don't know why.

**Comment by tetra-fox** [comment]
Fixed in 1fabeec

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
