### ISSUE TITLE
Option to disable Boot Sound

### ISSUE THREAD

**Issue by darth62969** [PFCKrutonium/Windows-10-Login-Background-Changer#105]
since we have to update the app to work with KB3081424, why not add an option to disable that annoying boot sound that came with it? This is a must as it was one of my most hated things from 7. not letting it creep back after 10 was so good, before hand.

**Comment by tetra-fox** [comment]
There isn't one?

**Comment by darth62969** [comment]
there was not until the latest update, now with the same update that broke the app, MS brought back that old familiar windows 7 sound. i really want to  be able to disable that.

**Comment by SkullyKiddo** [comment]
@darth62969 Do you have the mapping of where does the boot sound flag is set? If nothing changed from Windows 7, this is the one:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\BootAnimation\DisableStartupSound

Setting to 1 will make the sound disabled.

It could be another switch on the "Application Settings" section.

**Comment by darth62969** [comment]
don't know but i do know that when i updated my system to the version that broke the app, the first thing i heard when it rebooted was the old 7 logon sound, don't know if that was a glitch though.

**Comment by darth62969** [comment]
it is still there, but i did upgrade from windows 7

also did not mean to close this.

**Comment by SkullyKiddo** [comment]
It's a pretty basic functionality. I'll only have time tomorrow morning tho.

**Comment by SkullyKiddo** [comment]
Working on it. I don't think this is the application focus tho. It surely would help the user, but its name (windows 10 background changer) defines what it will be doing, if we begin adding things to it we'll surely lose the focus. I'd suggest closing this issue.

**Comment by Toyz** [comment]
Maybe someone should make a Windows 10 Tweaks program? I mean I already made a OEM information editor

**Comment by darth62969** [comment]
yeah we should, but we have to figure out that all we can change via the registry and what all else is possible via not destructive methods.

**Comment by emmatyping** [comment]
I created an organization [Windows10Tweaks](https://github.com/Windows10Tweaks), and I think we should put things under that roof. Whad'ya think?

**Comment by darth62969** [comment]
this has been solved and taken care of.
