### ISSUE TITLE
Suggestion: pre-package CLI in releases

### ISSUE THREAD

**Issue by tjhorner** [PFCKrutonium/Windows-10-Login-Background-Changer#120]
It gets rid of the need for people to clone, open in VS and then compile.

**Comment by Toyz** [comment]
there is on in the release section?

**Comment by tjhorner** [comment]
The command line application?

**Comment by Toyz** [comment]
aa that one we should be packaging as its own program soon

**Comment by tetra-fox** [comment]
@tjhorner wasn't ready for release before. now it is. will be included in v1.0.2.1

**Comment by Krutonium** [comment]
It's now out in 1.2.0.0

**Comment by tjhorner** [comment]
Great :+1:

**Comment by Krutonium** [comment]
:+1:
