### ISSUE TITLE
Release 1.0.2.0 Screen Flashing Error

### ISSUE THREAD

**Issue by 5donuts** [PFCKrutonium/Windows-10-Login-Background-Changer#127]
I downloaded release 1.0.2.0 from [the releases page](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases) and selected "use current accent color," which is a dark grey. I then used `WIN+L` to lock the screen, however the lock screen did not appear.

Instead, the solid light grey screen with the loading circle of spinning dots appears for a couple frames, then the "lock screen" (or whatever it's called; the one with the background you can actually change in the windows 10 settings menu, it has the time & date, etc. and the actual login screen swipes up from the bottom of it) appears for a couple frames and this process repeats indefinitely (I waited ~1 min before removing the battery from my computer to force it to shut down since my power button apparently only puts it to sleep in that menu).

Thankfully, I was dual-booting arch, so I could easily go and read then implement [the recommended fix](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login) to fix my system. Unfortunately, I did not think to save the broken `pri` file at the time, instead only restoring the backup to return my system to normal functionality.

I believe this error may be similar to [#106](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/106), however the comments were too vague for me to confirm.

EDIT: I was able to recreate the issue and obtain a broken `pri` file, it can be downloaded [from ge.tt](http://ge.tt/3DfoMtL2/v/0) Additionally, if it will help identify the issue I can try to get some video of the screen flashing, though I would prefer no to bork my computer again.

**Comment by Toyz** [comment]
the current color accent is a werid feature cause it just sets a solid png as your background which then is used to get your current color...

nothing i can do about it honestly

but that may be a link to why it's breaking logons lemme check it out

**Comment by tetra-fox** [comment]
@Toyz I've seen the flashing screen issue before in action, in a skype call. It basically just alternates between the lockscreen and the accent color every 500ms.

**Comment by darth62969** [comment]
we know, and i am currently trying to power though that release to find a work around as to why it is not working. (to get it to work, it works on my desktop but not on the vm i am running)

**Comment by ashoksoni** [comment]
@darth62969 
I think it's better if you warn users about not changing their background if they updated to Windows 10 rather than having a clean flash Windows 10..
I learn that the hard way when I was googling about this cause cause I updated my Windows 10 on Windows 10 cause of some issues I was having..

Anyways since I didn't have any password to my account, I was lucky enough not to stuck anywhere as restarting made me login to my account without any issue and then googling helped me to set the settings to default. Then I restored a backup of my old Windows 10 setup and it worked fine. 

So I guess putting up a warning would help so many others. Thanks for the nice program though. :)

**Comment by iconmaster5326** [comment]
I used version 1.0.2.0 of this tool to change my login screen to solid black using the solid color selector, and this bug happened for me as well. With judicious application of System Restore, I got my machine back to working order. Just wanted to post this here to confirm the bug occurs for me as well.

**Comment by jasen123** [comment]
i have the same issue. i have downloaded background changer and when i locked my account the screen keeps on blinking blue between my lock screen and my logon screen. i cant do anything. please anyone help me!

**Comment by 5donuts** [comment]
Just follow the instructions on [this page](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login), that's how I got my computer to work again.

**Comment by jasen123** [comment]
Bro i cant do the step 4 it says the system cannot find the path specified. Pleease help me bro

**Comment by jasen123** [comment]
@5donuts. I cant do the cd windows\systemresources\windows.ui.logon\ 

Look

**Comment by 5donuts** [comment]
What's the output of `echo list volume | diskpart`?

**Comment by jasen123** [comment]
bro its okay now, i used c: not d: Thank you so much for your help. Godspeed!  

```
 On Tuesday, August 11, 2015 9:16 AM, 5donuts <notifications@github.com> wrote:
```

 What's the output of echo list volume | diskpart?—

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Comment by jasen123** [comment]
Greetings! 


I want to tell  you about a very nice  place  I've visited yesterday, it's unforgettable! Just take a  look   <http://lyltalyha.awgale.com/lnfitgn>

Warm regards, VIAGRA  CIALIS

**Comment by jasen123** [comment]
Yo! 

I wanted to  share with you something important , I guess I really and truly am in love this time! Take  a look at  some  pics of us   <http://wefresheko.frabizziolaw.com/lngimok>

VIAGRA  CIALIS

**Comment by emmatyping** [comment]
~~I've temporarily locked this conversation due to some spam we are dealing with.~~
Resolved. Please comment if needed.
