### ISSUE TITLE
Login screen is broken

### ISSUE THREAD

**Issue by CapnKitten** [PFCKrutonium/Windows-10-Login-Background-Changer#131]
Version: 1.0.2.0

Login screen was in an infinite loop at first. After I restarted my computer, it would show the lock screen, and if I clicked it to login, it would just show a colored background with nothing on it.

I used this method to fix it: [Can't Login](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

**Comment by tetra-fox** [comment]
So, did it work?

**Comment by CapnKitten** [comment]
The fix worked, but I haven't tried the background changer since I fixed it.

**Comment by tetra-fox** [comment]
Okay cool, please close this issue, if it was resolved.
