### ISSUE TITLE
Screen flashing error 

### ISSUE THREAD

**Issue by leyyce** [PFCKrutonium/Windows-10-Login-Background-Changer#134]
Hello guys, 
first of all I want to give you my settings for the background changer:
-new picture 
-fit resolution to screen 
-disabled profile picture 

Now my problem... 
I used the above setting and then locked my screen to test them. Since then my screen just keeps flashing and won't show the login screen. I tried to replace the files with cmd exactly like u wrote it in the How to fix it section and the screen is still flashing. 

After that I even tried to edit the registry so that the loginsscreen won't show a picture but the windows colors. Still keeps flashing. 

Someone of you have some ideas how to fix this?

**Comment by darth62969** [comment]
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login

**Comment by tetra-fox** [comment]
you have been featured in that wiki page

**Comment by leyyce** [comment]
Thanks for the fast reply, but did you read my question? ("I tried to replace the files with cmd exactly like u wrote it in the How to fix it section and the screen is still flashing.") I have tried these steps and it's still not working

**Comment by JDesignEra** [comment]
Try this without ", all in one line. Change C: to your OS installed drive.

"copy C:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri.bak C:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri"

When prompt to overwrite type y.

**Comment by leyyce** [comment]
Thanks for the reply, but like i said I tried to replace the .bri file serveral times (over cmd and over my Win7 installation on second partition). My screen is still flashing. Is it possible that i have to replace the Windows.UI.Logon.de-DE.pri file (7kb) in X:\Windows\SystemResources\Windows.UI.Logon\pris. Also would it be possible to upload a working Windows.UI.Logon.pri file so i can be sure that the file is working. And is there maybe some other file that I have to replace (maybe SFC /SCANNOW could solve the problem?)

**Comment by leyyce** [comment]
Edit:
sfc /SCANNOW can not solve the problem it told me that the .pri (modified and backup)  file is broken but it failed to solve the problem :(

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
