### ISSUE TITLE
Login screen is broken

### ISSUE THREAD

**Issue by Mike-Austin** [PFCKrutonium/Windows-10-Login-Background-Changer#139]
First the screen went black, then it started flashing between lock screen and login screen. To fix, I just replaced the .pri file from a backup image. I can supply the modified .pri file if required (size increased from 2.1Mb to 21Mb!)

**Comment by Toyz** [comment]
you must be using a high DPI image

think of a PRI like a zip file with 10 copys of the same image

you need to keep the image sizes rather small or it breaks Windows.UI.Logon.pri i am working on a way to prevent this frmo happening

**Comment by Mike-Austin** [comment]
Thanks. Yes, it is a detailed image - one that I use across all my devices (and on the Windows 10 lock screen). Is there a definitive image size to use?

**Comment by Toyz** [comment]
Yea I tested a detailed image and figured out a image that was 1.01mb saved to my HD was actually 3.4mb in memorystreams which is whats required to write to the file

**Comment by Mike-Austin** [comment]
Hi Toyz,

I closed the thread, but my latest attempts still cause the same problem. That is despite reducing the resolution to 800x450 (half of my laptop’s resolution) with a file size of 118Kb (1,140Kb in memory). The resulting .pri file size was 3,074Kb. I will give up on this for the moment. There are enough bugs in Windows 10 to sort out before I play with the cosmetics!

Mike Austin

**Comment by Toyz** [comment]
That's cause the file stream is like 1mb it pends on how detailed the image is look at my recent post on issues that's label with wontfix it explains why this happens
