### ISSUE TITLE
Login screen is broken

### ISSUE THREAD

**Issue by gosteev** [PFCKrutonium/Windows-10-Login-Background-Changer#140]
hello. reporting you an error. 
here's the image i used
![girl-playing-space-invaders](https://cloud.githubusercontent.com/assets/6203574/9168154/5aceb500-3f5f-11e5-8ae4-ab574fb3a925.jpg)
version - 1.0.2.0
screen res - 1366x768

also i tried to resize image to my screen res (though after resizing it was 1365x768) - same result

**Comment by Toyz** [comment]
Testing image now:

Results: Worked on Windows 10 most recent build and all updates including the cummlitive update

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
