### ISSUE TITLE
[SOLVED] Windows 10 is screwed up.

### ISSUE THREAD

**Issue by TheCypher1** [PFCKrutonium/Windows-10-Login-Background-Changer#141]
Alright lads, here's my problem. Got the latest version of this software on Saturday, made my own custom image for placement into the background. Screen starts flickering; did a System Reset, lost all my programs but that's no problem, full of crap pre-installs anyway. Kept my files, thought everything was solved. However, I tried to install official Windows updates yesterday (Sunday) and after they were installed it did the flicking logon screen thing AGAIN. Did yet another system restore, and now I'm lost. I've created a Restore Point in the event it tries to install updates again, but I'm honestly stuck. I've seen solutions on here but someone did the exact same thing as I did however tried the solution and now he had a black screen so I'm not doing that.

Help me lads, you're my only hope.

**Comment by darth62969** [comment]
do you have the Windows.UI.Logon.pri.bak file still?

**Comment by TheCypher1** [comment]
Afraid not: 
![that thing called untitled that never gets deleted](https://cloud.githubusercontent.com/assets/5618486/9171953/aaa54370-3f67-11e5-9cbb-1d8d97c7f469.png)

**Comment by Oleg015** [comment]
I am stuck at the same point, even my windows log in every time with a normal user 
then ai cannot log out to select another user

People who made this crap should burn in Hell forever

**Comment by TheCypher1** [comment]
Now, now @Oleg015, there's no need for that.

**Comment by Bryan-Devenish** [comment]
I'm having the exact same problem as well, i'm running the commands as shown on the test example/video. But my computer simply doesn't contain the .bak file. Couldn't the developer just upload the .bak file for us, so we can drop it in manually. Then we could hard reset again and follow the same command prompt process?

And I agree, no need to get rude over this Oleg. You're entitled to get pissed off, but lashing out at the developers wont motivate them to sort this out.

**Comment by TheCypher1** [comment]
Bryan, go here: https://plus.google.com/u/0/+TheCypher/posts/5fGYHjEt7NV I have a guide on fixing the issue you have. Just scroll down the comments and you'll find it.

**Comment by Bryan-Devenish** [comment]
@LordCastabarus Hm i'm not sure I understand the process described. So i'll write out how I percieve it to be, like so:

• Reset windows, in order to return to the desktop (Windows 10 Fresh Upgrade / No updates Applied)
• Run the WindowsBackgroundChanger again, but use the image posted in the reply as the logon background? (The one with the Anime girl and floating guns?)
• Enable the lock screen to re-produce the error again, install the Windows cumulative updates

• Then what do I do? Because it's stated to run Command prompt and copy what's in the video. But in the video above there's no use of the Command Prompt what so ever.
Or..
• Then do I run the command lines to delete the Windows.UI.Logon.pri, then using the .bak to replace it?

I'll update this when I get somewhere.

**Comment by tetra-fox** [comment]
• Then do I run the command lines to delete the Windows.UI.Logon.pri, then using the .bak to replace it?

**Comment by TheCypher1** [comment]
'Reset windows, in order to return to the desktop (Windows 10 Fresh Upgrade / No updates Applied)'

No. You see I just dived straight into it without trying to update again. Updating again may fix the problem, but just to be sure, create a restore point so you don't have to reset Windows for a third time if it flickers again.

'Run the WindowsBackgroundChanger again, but use the image posted in the reply as the logon background? (The one with the Anime girl and floating guns?)'

Yep. I know it sounds bizarre but it's the image that worked for me. I can't verify that other images will have the same effect.

'Enable the lock screen to re-produce the error again, install the Windows cumulative updates'

Indeed; and any other Windows updates that may be pending.

'Then do I run the command lines to delete the Windows.UI.Logon.pri, then using the .bak to replace it?'

Yes. I forgot what videos I was posting the guide on, here's what I meant by following the steps in the video: https://www.youtube.com/watch?v=W_eHZZW1ung (Thanks Syrexide)

If you have any further questions, feel free to let me know!

**Comment by Toyz** [comment]
The most recent cumulative update that was released on the 11th fixed tons of issues

**Comment by Bryan-Devenish** [comment]
@LordCastabarus Hey man, thanks a ton! My windows seems to be working fine, even with the updates. I compiled a easy to read guide based on your fix here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186

Hopefully this will help out other people with the same problem.

Edit: <b>If you've come from the Wiki page seeking a fix, follow the link below. You'll be taken to a guide to correct your Login Screen

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186</b>

**Comment by TheCypher1** [comment]
@Bryan-Devenish No problem mate :)

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
