### ISSUE TITLE
Login screen is broken

### ISSUE THREAD

**Issue by ghost** [PFCKrutonium/Windows-10-Login-Background-Changer#142]
Latest Release 8/10/2015
![7fl5i](https://cloud.githubusercontent.com/assets/13615574/9172033/b8361874-3fb3-11e5-8550-3ae58d3484aa.jpg) - didn't keep the .pri file, sorry.

**Comment by Toyz** [comment]
Testing image now:

Results: Worked fine on Windows 10 most recent dev build

**Comment by TheCypher1** [comment]
@Toyz If I download the newest version you just released and add a new image, would it fix my Cumulative Windows update problem?

**Comment by Toyz** [comment]
I used it and had no issues in applying your image at all

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
