### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by Prototyper47** [PFCKrutonium/Windows-10-Login-Background-Changer#166]
Hi!
I used this tool (latest version downloaded from here) and my lockscreen started to blink. I had to change the pri file from the second OS. Now I send you the broken one:
https://www.sendspace.com/file/ecq9ld
The only thing I have changed - set the default color instead of any image.
Hope this will help.
Regards, Stan

**Comment by emmatyping** [comment]
Could you upload the image too? Also, please read the wiki if you haven't already.

**Comment by Prototyper47** [comment]
Hi! As I told you - I didn't use any image, I chose "Use accent color" option. Maybe it's all about Win10 Home Single Language? There's always problem in tweaking it :(

**Comment by darth62969** [comment]
uh... i run home and i have not had any issues. there are a few machines that do. particularly i think it is lower end machines, but don't quote me on that. if i may say it seems that most of the devs have higher end machines some more so than others. can you post your specs? i want to get a better grasp of who has what issues.

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
