### ISSUE TITLE
lock Screen is Broken

### ISSUE THREAD

**Issue by gearcapitan** [PFCKrutonium/Windows-10-Login-Background-Changer#170]
I too feel the same, if I can change the screen where I put my password, but the lock screen that slides up, is damaged and can not see, only a few points listed in a circle and immediately the screen turns to put my password and restore the file Windows.UI.Logon.pri.bak achieved but still nothing works, anyone know how to fix that?

**Comment by tetra-fox** [comment]
You can fix this [here](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login).

**Comment by leyyce** [comment]
Don't even try it... I wrote 3 times that I replaced the .pri file and i got 3 replys with a tutorial how to replace the .pri file. They don't even read your qustion :(

**Comment by emmatyping** [comment]
@iElCapitan just because something doesn't work for you doesn't mean it won't work for others.

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
