### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by loldev69** [PFCKrutonium/Windows-10-Login-Background-Changer#171]
using ![release 1.0.2.0](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.0.2.0)

image used

![defcon3](https://cloud.githubusercontent.com/assets/13751360/9202718/802a8ab4-4053-11e5-8ad6-eb3958e9cf6b.jpg)

.pri file that failed renamed with .png extension to piss off github (just change it back)
![failed](https://cloud.githubusercontent.com/assets/13751360/9202788/cd90c5e8-4053-11e5-9a79-4a2dbc6ae2fb.png)

the result was a black screen that sometimes flashed the proper image and was apparently impossible to interact with

**Comment by Toyz** [comment]
Could be to much detail cause of pri loading time out, if your PC takes to long to load the Pri it times out

**Comment by tetra-fox** [comment]
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
