### ISSUE TITLE
Error While Open OpenFileDialog of Picking Image

### ISSUE THREAD

**Issue by iwih** [PFCKrutonium/Windows-10-Login-Background-Changer#172]
In class W10_BG_Logon_Changer.Controls.BgEditorControl.xaml.cs, in method "private void Button_Click(object sender, RoutedEventArgs e)" line 64, I replaced the following code:

``` c#
    if (!string.IsNullOrEmpty(Settings.Get("last_folder", string.Empty)))
            ofd.InitialDirectory = Settings.Get("last_folder", string.Empty);
```

with this code

``` c#
    var initialDirectory = Settings.Get("last_folder", string.Empty);
                if (!string.IsNullOrEmpty(initialDirectory))
                    if (Directory.Exists(initialDirectory))
                        ofd.InitialDirectory = initialDirectory;
```

The original code gets the last directory even when its not available currently, which throw a "The system cannot find the drive specified" error. So, it must be check for existence.

Thank you for the fabulous application.

Kind Regards,
Osama Alwash

**Comment by darth62969** [comment]
@Toyz  has this been fixed?

**Comment by emmatyping** [comment]
This was still in v1.0.2.0  I will download newest release and look.

EDIT: And it is still in v1.2.0.0

And I made a PR to fix. [#216](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/pull/216)

**Comment by emmatyping** [comment]
Merged, should work now.
