### ISSUE TITLE
Login Screen Broke

### ISSUE THREAD

**Issue by Tarkin15** [PFCKrutonium/Windows-10-Login-Background-Changer#174]
Hi,
My loginscreen broke after using the program, the screen was flashing on and off of the loading icon after swiping the lockscreen image up. The program version was 1.0.2.0 and I used the wallpaper usually found in "C:\Windows\Web\Wallpaper\Theme1\img4.jpg"
![img4](https://cloud.githubusercontent.com/assets/13752753/9205530/a1ade0ee-405a-11e5-8d03-668b5ff13580.jpg)
Also here is the .pri file: https://mega.nz/#!ctMm3bjb!26EL8d4TPwMGHUTWgLarRtqfT1AjbLZlaiYmm0Vpb_E 
Thanks :)

**Comment by Toyz** [comment]
It could be the image it's a tad detailed which would cause the load timeout have you tried a less detailed image?

**Comment by Tarkin15** [comment]
Yeah, just tried this one:
![windows_insider_ninjacat_trex-1366x768](https://cloud.githubusercontent.com/assets/13752753/9206639/ea695f42-4060-11e5-9e3b-c11f1428c292.png)
Sadly had the exact same issue.

**Comment by Toyz** [comment]
Ok yea it's a issue with the most recent cumulative update Microsoft hasn't released there patch to it yet

**Comment by Tarkin15** [comment]
That's a nuisance, thanks for the help :)
