### ISSUE TITLE
[SOLVED] Login Screen is Broken - Fix for anyone missing the .bak File

### ISSUE THREAD

**Issue by Bryan-Devenish** [PFCKrutonium/Windows-10-Login-Background-Changer#186]
Hey guys, I was able to repair my system and install the latest updates returning it back to normal. Before I explain the steps I took, I would like to thank <b>LordCastabarus/The Cypher & Syrexide</b> for providing two possible methods that I ended up combining.

<b>IMPORTANT, please read!</b>
Now before you begin attempting to use this guide to fix your computer, please follow this at your own discretion. Please give the entire guide a proper read over, before committing to these steps. As this might not work for everyone's computer/laptop. But as for me, this is how I fixed my issue in regards to having a missing .bak file.

![divider 2](https://cloud.githubusercontent.com/assets/9061213/9234132/e10c837e-412e-11e5-831f-6a68d9b08337.png)
<b>Part one -</b> "Determine whether you have the .bak file or not."

<b>Step 1:</b>

<b>Option 1:</b>
If you have access to your desktop screen after doing a fresh reset, that restored Windows to its default settings. Open up File explorer and follow this path <b>"C:\Windows\SystemResources\Windows.UI.Logon"</b>. If you're lucky, you might see two files. <b>Windows.UI.Logon.pri & Windows.UI.Logon.pri.bak</b>, but the chances are the .bak file wont be there. If the .bak is indeed there, go ahead and skip to <b>Part 2, Step 1</b> below.
![divider](https://cloud.githubusercontent.com/assets/9061213/9232456/a85d986e-4125-11e5-8975-44991fde965f.png)

<b>Option 2:</b>
If you're unable to access the desktop, you can hard reset you PC by holding the power button 3 times after you've loaded the Login screen. This will start up Windows Recovery Options, once loaded you'll be introduced to limited options. Follow this path to load the Command Prompt, <b>Troubleshoot>Advanced Options>CommandPrompt.</b>

Once loaded, you'll need to figure out which partition contains your Windows Files. For example mine are installed on my C: Drive, however on Command Prompt it can be given an alternate name. The easiest way to recognise this is to check the storage size, for example my Windows drive is 435Gb. So it'll be listed as <b>Volume ? ? NTFS Partition 435GB Healthy Boot.</b>
![divider](https://cloud.githubusercontent.com/assets/9061213/9232710/15877aee-4127-11e5-98f8-09a8e2567651.png)

<b>Type in the following command lines once you know where your Windows is installed, to find where the .bak might be on your Windows drive:</b>

<b>1.</b> echo list volume | diskpart
<b>2.</b> c: <b>(Replace "c" everytime with whatever partition your Windows is installed on)</b>
<b>3.</b> CD c:\Windows\SystemResources\Windows.UI.Logon\ <b>(Press Enter)</b>
<b>4.</b> DIR <b>(Add DIR on the end of the new line that appears)</b>
<b>5. After entering DIR, you'll see the contents of this folder where the .pri and .bak should be.</b> If you only see the .pri and no .bak continue on with this guide.

<b>Note -</b> If you don't have the <b>|</b> & <b> \ </b> keys like me. Hold Alt and press the following codes with the right numberpad on your keyboard.

<b>ALT</b> + <b>124</b> = |
<b>ALT</b> + <b>92</b> = \

If you end up not being able to navigate the command prompt easily, do not worry. Continue towards to the next step to get the Desktop back. By doing this you can check for the .bak in the Windows folders and if it's still not there. You can still fix your problem via being on the desktop.
![divider](https://cloud.githubusercontent.com/assets/9061213/9232463/b07d1664-4125-11e5-95f4-2355f36e6436.png)

<b>Step 2:</b> Getting to the Desktop <b>(SKIP this step if you already have access to the desktop)</b>

Now if you're currently unable to return to the desktop follow the steps below. But before I begin to explain the following steps, I want to warn you that theres a possibility of losing personal files. Therefore attempt this option at your own risk, you've been warned. However I've tried all types of the resets before and you should be able to keep your personal files. First things first, follow this path <b>Troubleshoot>Reset Your PC.</b> You should then see the following -

![reset 2](https://cloud.githubusercontent.com/assets/9061213/9231638/1e8835f8-4121-11e5-969a-25bb9077e6f9.png)

<b> Keep my Files -</b>
Saves your personal files and resets Windows to the fresh upgrade version

<b> Remove Everything -</b>
This will remove everything by completely resetting your Windows and will offer you the screen below to clean out any other drives. <b> Don't worry too much about doing a complete wipe,  just reseting and keeping your personal files should be enough.</b>

![divider 2](https://cloud.githubusercontent.com/assets/9061213/9232808/acc07654-4127-11e5-87a1-650e1396413e.png)
![reset 3](https://cloud.githubusercontent.com/assets/9061213/9231639/1e88b956-4121-11e5-9aff-f32a4e03f7da.png)

<b>WARNING - Proceed with these options at your own discretion. As you might lose personal files</b>

<b>Note -</b> It might ask you to login into your Microsoft account, simply login and click reset.
![divider](https://cloud.githubusercontent.com/assets/9061213/9232339/08e5c0cc-4125-11e5-9704-32257a326938.png)
Once you're done choosing, you should see your computer restarting and the Windows Logo should appear. Let it reset your PC and within no time you should be back at a functional login screen. But it's very important <b>NOT TO UPDATE</b> your Windows at this time. As you're still at risk of the bug returning.

![divider 2](https://cloud.githubusercontent.com/assets/9061213/9234464/dd3d710c-4130-11e5-8034-f43d81f095ac.png)

<b>Part Two -</b> Replacing the .bak file

The next step requires you to re-run the Background Changer application but with certain files provided below that should produce a .bak file. But make sure you stay away from Windows Update for the time being.

<b>Step 1:</b>
Download the following items from MediaFire link below which should contain two items. The first being a wallpaper and the second being the Background Changer Application. 

https://www.mediafire.com/folder/4uonlnng94y5t/Background_Changer_Fix

<b>Wallpaper Image: (Just in case the Media Fire one messes up)</b>
![b8361874-3fb3-11e5-8550-3ae58d3484aa](https://cloud.githubusercontent.com/assets/9061213/9232166/152a32c4-4124-11e5-8832-f3c5d9a31a6e.jpg)
![divider](https://cloud.githubusercontent.com/assets/9061213/9233694/6db3b5f2-412c-11e5-94ca-51112430a3b0.png)

<b>Step 2:</b>
Extract all the contents to the desktop, so you should have the wallpaper Image and the extracted Background Changer Zip folder contents (the .dll files and the .exe). Run the <b>WIN10 BG Logon Changer.exe</b> and use the image supplied as your new lock screen. Click browse, find the wallpaper image on the desktop and apply the changes.
![divider](https://cloud.githubusercontent.com/assets/9061213/9233686/66b6b218-412c-11e5-818f-e0e81fdfc795.png)

<b>Step 3:</b>
Now go to settings <b>(Start > Cog Icon)</b> and click on <b>"Update and Security"</b>, then click check for updates. Before closing this window, at the bottom it should say "Advanced Options". Click on that option and change the way it'll update underneath <b>"Choose how updates are installed".</b> Change it from <b>Automatic (Recommended)</b> to <b>Notify to schedule restart.</b> This will stop Windows from automatically restarting the pc when the updates are downloaded and installed. 

Now whilst they're downloading and installing. Do nothing else at this time, other than setting up a backup plan just in case the next step gets difficult. Grab a burnable disk or USB Thumbstick and download the exact same OS of Windows you're currently running on. To find out which version you're running go back into settings and click on <b>Update and Security</b> and click on <b>Activation</b>. Here it should label what version of Windows 10 you're running. Once you know what Windows OS you have, follow the link below.

• https://www.microsoft.com/en-gb/software-download/windows10

Download the correct 32bit or 64bit installer onto either the disk or USB stick. Once downloaded follow the steps provided whilst running the installer, to create an installation boot media that corresponds to the version of windows you're using. 
![divider](https://cloud.githubusercontent.com/assets/9061213/9233663/47415578-412c-11e5-8793-bf75bbcbada3.png)

<b>Step 4: NOTICE -</b> In the event of not being able to return to the recovery screen. Go to Option 2.

<b>Option 1:</b>
Once you have all the Windows Updates installed and you have the Backup installation boot media on a disk/USB. You can now restart your computer. Allowing Windows to apply and configure the latest updates. Once it's done installing, you'll return to the login screen with the bug. This is meant to happen as you've just created a logon screen that should provide a .bak to repair it.

Now hard reset your PC three times and return to the recovery options screen. Follow the path <b>Troubleshoot>Advanced Options>Command Prompt</b>.  Then follow either the text example below or watch the video provided by Syrexide and reproduce the same steps.

<b>Video Example -</b> 
https://www.youtube.com/watch?v=W_eHZZW1ung

Or try,

<b>Text Example -</b> 
![command line example](https://cloud.githubusercontent.com/assets/9061213/9233474/2cf8c080-412b-11e5-9415-26b2f42920ec.png)

<b>Note - </b> See Part 1, Option 2 to figure out how to find your Windows Partition letter.
![divider](https://cloud.githubusercontent.com/assets/9061213/9233566/b1642b7a-412b-11e5-922d-69771fc533ed.png)
Now once you've followed the steps from either the video or text example, you should now be able login, complete all windows update, restart you computer and then still be able to login. You should be all good to go from here on out! Congrats! :D 
![divider](https://cloud.githubusercontent.com/assets/9061213/9233805/049c749a-412d-11e5-9943-2c08c6e1af2e.png)

<b>Option 2:</b>

<b>Step 1:</b>
Now in the event of the recovery options menu not loading after 3+ hard resets, you'll need that handy disk/USB stick backup plan you made. Like me, for when I attempted it, I wasn't able to get the recovery options menu to load at all. However to resolve this, when my computer initially loads I'm given a splash screen that tells me what F key to press to get to my boot menu. 

By pressing F12 (That's for my system, might not be the same for you) my screen shows a very basic menu with all my drives listed. Look for the one labeled as Disk or USB and press enter on it (Navigate to it by using the arrow keys). This will restart your system and it'll attempt to load the installation boot media you created earlier and you'll be presented with a screen like this:

![repair](https://cloud.githubusercontent.com/assets/9061213/9233886/8fc1004a-412d-11e5-9002-7dc929dd53e7.png)
<b>Yes I know it says Windows 8, but the Windows 10 has the exact same layout</B>
![divider](https://cloud.githubusercontent.com/assets/9061213/9233928/bb24da36-412d-11e5-88bf-c6144bc28c54.png)

<b>Step 2:</b>
On the bottom on left of the window shown above you'll see <b>"Repair your computer"</b>. Click no this option and you should be taken to a purple Recovery Options menu. Follow this path to get to the command prompt, Troubleshoot>Advanced Options> Command Prompt. Once the command prompt has loaded, return to <b>Step 4 and follow Option 1.</b>

![divider 2](https://cloud.githubusercontent.com/assets/9061213/9234283/c3a5c2ea-412f-11e5-883c-3a2f6d567f9a.png)

Sorry if this didn't work out for you or if it made it worse, but I did state at the start that this might not work or worsen your situation. However if it didn't and it did solve it! Avoid this app as for the near future, until Windows 10 has become more stable itself.

**Comment by emmatyping** [comment]
It would probably be better to put this on the Wiki, and not in the issues.

**Comment by TheCypher1** [comment]
*Cypher

I usually go by The Cypher now, I just never got round to updating this account's username.

I do hope this guide helps anyone experiencing this annoying issue. My system seems to be back to normal and starting faster now. I believe after I restored a second time, a second copy of Windows 8.1 was created on my hard drive, which Windows 10 later deleted by itself. I believe that was causing the slow start up.

**Comment by alitokii** [comment]
(Option 1 is the one I used)After I deleted the bak file and tried to do the copy thing, it says the system couldn't find the file, did I miss a step or anything? Thanks!

**Comment by UberRoss** [comment]
I've followed the steps so far up to Part 1; Option 1; Step 2, and for some reason when I choose to reset my PC, it goes up to 8%, and boosts up to 53% before returning to the recovery menu and saying that there was a problem resetting my computer, and no changes were made. No matter how many times I try, it doesn't work.

Am I screwed?

**Comment by Bryan-Devenish** [comment]
Do you have a Installation boot media? If so make sure you boot your PC from it and try re-installing it via that approach, or return to the Advanced Recovery menu and do the simplest reset option and try again.

However resetting/reinstalling Windows can take any time from 20 hours+. So try to give it a chance, failing that, I too noticed that my installer kept stopping or going blank at certain points. Shutting down your PC and loading it again will resume the installation again. It could be that it simply got stuck, found an error or crashed. Make sure you unplug any unnecessary items as well, as you want it to just fly through and not find drivers for all your accessories.

**Comment by UberRoss** [comment]
Your advice came too little too late, I'm afraid. I did indeed have a Windows 8.1 installation boot media, and the only thing I could think to do is to revert to Windows 8 and start my upgrade all over again from a clean slate, inevitably losing all of my data. Thank goodness for backups, though! It's the unfortunate price I had to pay for a login screen that doesn't look dumb. I just wish Microsoft would've built something into the login screen to where you could change it without having to risk using third party tools. My only concern is that when I upgrade back to Windows 10 from 8.1, will the login screen return to normal and I won't have to do this whole rodeo again, or am I forced to stay in Windows 8.1 until further notice?

**Comment by KaleidonKep99** [comment]
You can eventually force a System Restore by using the Installation Support (CD or USB), like I did.
You'll lose\* new programs, but it's worth it.

**Comment by Bryan-Devenish** [comment]
Exactly, that's one way. But you can acces the command prompt a many of different ways. Just make sure you're all backed up and confident. If you read the guide, it's safe to update and upgrade to Windows 10. Including all their latest updates. Not only that, but if the error occurs again at least now you have the guide to fix it for good.

**Comment by thoroc** [comment]
Option 2 is prolly wrong: had to hard reboot three times at exactly the windows logo screen and before getting to the login screen, otherwise that would not work.

**Comment by Bryan-Devenish** [comment]
Everyones system is different, but mine was initially like that. But after the reset it wouldn't attempt it until I reached the Login screen. Hope it did work, reply here otherwise.

**Comment by tetra-fox** [comment]
You do not need this fix, as of v1.0.2.0

**Comment by wynsx** [comment]
How to Rename or replace pri file with live linux to fix cannot login due to failure changing login background: youtube.com/watch?v=KGcfvEwqSGc

**Comment by darth62969** [comment]
moved to wiki. thanks @Bryan-Devenish

**Comment by Kkeilo** [comment]
I followed step 1, option 2 and i did not have the .bak file in there. So I went on to trying to reset the pc. But it wont allow me, it says "Could not reset this PC. No changes have been done". (Direct translation from Swedish.) Any ideas?

**Comment by Bryan-Devenish** [comment]
There's a difference between repair and reset. Make sure you're not choosing the repair one as it wont resolve your issue, you need to reset you pc so it removes all installed applications and software. Leaving you with a thresh copy of windows 10, but with your personal files intact, minus the applications. If you continue with any more issues, just send me a reply and i'll try to help as best as I can. Good luck.

**Comment by Kkeilo** [comment]
I know, I tried both repair and reset. Neither worked, the PC would just say "could not repair" and "could not reset". However I managed to fix it. I had to boot MediaCreationTool via USB and do a clean reinstall via it. I am concerned that it refused to do a reset without MediaCreationTool. I usually have my laptop with me, would not want this to happen again when I don't have my USB with me. Anyways, Thank you!

**Comment by Bryan-Devenish** [comment]
Awesome, if it happens again once you update your Windows. Follow this guide again if need be and it might work this time around, even more so that you've been able to restore the desktop. Keep me posted if it gets worse. :)

**Comment by obethinho** [comment]
Hi Bryan-Devenish none of the solutions worked for me i tried and i tried and i still havent been able to see my login screen on windows 10 (still in black with only the arrow), now am in windows7 in this same computer cause i have install windows10 on a sdd and windows7 on a hdd! is it posible to download the content files from the C:\Windows\SystemResources\Windows.UI.Logon folder?? anyone could upload it? please?

**Comment by emmatyping** [comment]
@obethinho, that would break Microsoft's copyright. You may be able to boot off the other drive.

**Comment by Documer** [comment]
Guys I did a very Sinple thing.....I also did no have bak file in my system. I copied the file 'Windows.UI.Logon.pri' from my frined's system and replaced my corrupted file in the exact folder, through Ubuntu which I had already installed in my PC....... It worked perfect.....

**Comment by Bryan-Devenish** [comment]
@Documer That's great dude, but it isn't that straight forward for everyone. The bug infected more than one file, but when updating to the live version of Windows 10. The bug came back as the files weren't properly fixed. For some people this might work and for most it wont. I originally did what you had tried, which worked fine for 4 days. Then out of nowhere the bug returned, even though I had all the latest updates installed.

**Comment by realindiahotel** [comment]
Hello, I had the .bak file so I booted into the recovery command console and I literally deleted the .pri and I renamed the .pri.bak to .pri and I was good to go again. Your part 2 seems more complicated then it needs to be. Basically the end goal is to fix the corrupt .pri. Hopefully you can use the backup .pri.bak to revert the corrupt .pri. Thank you for getting me into the right folder to fix the .pri :)

**Comment by emmatyping** [comment]
@Thashiznets I am glad you were able to solve this, however, with the anniversary update, this tool no longer works. I am not sure it ever will again.

**Comment by realindiahotel** [comment]
Yes the tool breaks the .pri. Need to revert to .pri.bak to fix

**Comment by ghost** [comment]
Hi please I need help. At the step of command prompt, it shows me that there is no admnistrator on my computer. Please, I can't use the command prompt without an admnistrator account, how can I do??

**Comment by emmatyping** [comment]
@NoAdminUser if you boot into recovery command prompt, it is admin. You should be able to make the needed changes from that CMD.

**Comment by darth62969** [comment]
unless there is something else wrong with their computer and there is
literally no admin on the system...

(: Jonathan :)

**Comment by emmatyping** [comment]
Even then, unless their computer is _very_ very broken, I believe the recovery prompt should be admin...

If not, one should be able to boot recovery media and use that prompt.

**Comment by ghost** [comment]
Hi again. Actually, I didn't even know that there was no admin on my computer (how is that even possible? o_O) but I swear that in Recovery Repair boot, when I click on Command Prompt (or anything, I can't do nothing in troubleshoot because of that anyway) that it shows me that there is no Admin on my computer, and that I need to connect to an admin account to use the command prompt. 
(The irony is Windows telling me that I should connect to a session to change the Admin settings... _sigh_)
Should I try to boot from a bootable usb drive?

**Comment by emmatyping** [comment]
Yes, if it is rejecting your login credentials for admin, then I would boot on recovery media.

**Comment by darth62969** [comment]
I ran into a similar issue once... if there isn't a local admin that may
mean that It is a work or school computer. if that is the case then the
chance that recovery media will work is slim. You would need administrative
privileges to boot off anything other then the internal drive. Much less
change any system settings ot the damn thing isn't encrypted to begin with.

**Comment by ghost** [comment]
Uh-oh, I'm afraid you're right. I thinnk my computer used to be a work computer (I got it from my father that certainly got it from his office!!)
I haven't tried to boot from a recovery media yet, do you think I'm screwed? (I am no expert in computers, really...)

**Comment by darth62969** [comment]
NOt really... if you have control over the bios you should be fine. if you
don't... your screwed...

**Comment by kadzooks** [comment]
I would've _loved_ to use the method described in this to fix my broken logon image, but the steps involves erasing my computer data...

Data that can't be backed up and are hyper sensitive to tampering.
T-T

**Comment by KidComics** [comment]
For Option 2 Step 2 the Reset my PC option is not available. Suggestions?

**Comment by sethflip** [comment]
Thank you but I want to logon using  a live cd and replacing the logon file. If it works, I'll let you know.
I cant even change the default directory on the command prompt to the one containing my windows files.

**Comment by KthProg** [comment]
This didn't fix the issue for me.

**Comment by emmatyping** [comment]
@KthProg what did you try?

**Comment by KthProg** [comment]
All of the steps suggested, as well as copying a working .pri file from another computer. None of those solutions worked. I'm reinstalling Windows now after backing up all of my files. The solutions may not have worked because I have Windows 10 Education Edition.

**Comment by KthProg** [comment]
It wasn't your project that caused the issue anyways, it was another project that reskins Windows 10 to look more like Windows XP. It probably made similar but not exactly the same changes.

**Comment by emmatyping** [comment]
>It wasn't your project that caused the issue anyways, it was another project that reskins Windows 10 to look more like Windows XP.

Well if it doesn't modify the lock screen then these steps almost certainly won't fix your issue. Backing up and re-installing sounds like your best option.
