### ISSUE TITLE
Windows Recovery Options Won't Load

### ISSUE THREAD

**Issue by jegloff** [PFCKrutonium/Windows-10-Login-Background-Changer#187]
Hi Everyone

Even after doing a hard reset 3 times, my laptop will boot to "Preparing Automatic Repair" and then I'll get a blue screen saying "Your PC ran into a problem and needs to restart. We'll restart for you" along with the error code WDF_VIOLATION. Then the laptop will reset, I'll get the same message, it'll reset again, and it continues on like this. Slamming F8 continuously also does nothing. 

Because of this, I'm unable to access the"Advanced Options" button that would allow me to access  command prompt or really do anything. Does anyone have a fix for this?

**Comment by darth62969** [comment]
first we are not tech support, second do you have any installation media?

**Comment by jegloff** [comment]
Hi @darth62969 

No, unfortunately I do not.

**Comment by darth62969** [comment]
who is your manufacturer?

**Comment by jegloff** [comment]
Dell, it's an Inspiron N5110

**Comment by darth62969** [comment]
option 1: call dell, ask for parts. tell them you need installation media, give them your service tag, you will get your original OS for 10 bucks+shipping. if you have an optical drive use that, if you do not then go find someone that does. once you get it the installation media insert it and press the key for boot options, usually on a dell it is f12... it should be i just checked. select the optical drive. then when the screen that states "press any key to boot from disk" appears hit space or enter or whatever. you now want to use the installation to reinstall your previous OS. you want to click "install now", the next screen should have upgrade and install on it... upgrade should either be greyed out or not there, you want the bottom option. go through the prompts when you get to the screen that makes you select an installation drive, select your old windows installation. it will notify you that there is an older windows install on that drive and that it will put all old files and folder in a windows.old file. we want this if we want to rescue your files. click install... or next. it will install and you will have a working computer again... but without drivers, for this we need another computer with internet access. go to dells support site go to downloads and drivers. input your service tag and get all YOUR driver for your original OS... particularly the Graphics and the Network Drivers. put them on a flash drive and plug it into your computer. install them. then update your OS. while that is happening take you old user files from windows.old and move them to your new user file. then reinstall windows 10. 

Option 2. call dell say you broke your hard drive and "please send me a new one with all my programs and stuff on it." they will you install it. And you have a working computer except without your files. to get these take your old hard drive plug it in and go to your user folder and copy them over. at this point you can do what ever you want with the old drive. i recommend getting an external USB3.0 enclosure and using it as an external drive.

Option 3.... Geek squad. if any of these things scare you or you are not comfortable doing any of it this is by far your best option but most expensive. go to your local computer repair center and tell them that you need them to either fix the computer or reinstall windows and save your files. a good repair center will make this as seamless as possible.

why? you corrupted something. if your computer was trying to update, this probably happened. though that method is the most effective and easiest to do, it does carry the risk of screwing something up.  

Edit: this thread has more better info... https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186
in the event you don't have any recovery media, you still need to call dell to get the installation media

**Comment by darth62969** [comment]
I am going to close this one now, refer to #186 if you need further help. this should be fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
