### ISSUE TITLE
Login screen broken

### ISSUE THREAD

**Issue by Annhilate** [PFCKrutonium/Windows-10-Login-Background-Changer#188]
Flashes between lock screen and solid red repeatedly.
Was able to access files from another computer on same network and restore backup I created.
Release 1.0.2.0
link to broken file:

https://onedrive.live.com/redir?resid=97E263A5B3DEAF7A%21105

**Comment by wjwwood** [comment]
Same here.

**Comment by Bryan-Devenish** [comment]
Try following this guide to fix the login screen bug. https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Comment by Annhilate** [comment]
Great Job! Worked like a charm!
