### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by nolan879** [PFCKrutonium/Windows-10-Login-Background-Changer#190]
Tried to change the background, got a blinky screen, so I used your fix, now I cannot log in! (passwords aren't syncing with MS)

**Comment by Bryan-Devenish** [comment]
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186 - Try this

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
