### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by CasualSavage** [PFCKrutonium/Windows-10-Login-Background-Changer#191]
So this is the problem I have, it's impossible for me to login to my computer, in the video I show you the full process from restarting my PC:
https://www.youtube.com/watch?v=fV93Y4Ax1wM

For those wondering why I don't use advance options or anything else that is available on booting, it's because it always gets stuck on this screen in the video below. On this certain screen the mouse and keyboard all of a sudden just stop working, I have tried 3 different keyboards and 3 different mouses but still having the same problem:
https://www.youtube.com/watch?v=egKGWKQECZA

Not sure if this can be fixed but I'll appreciate some sort of help, thanks.

**Comment by Bryan-Devenish** [comment]
You can always try to use an installation boot media to get to the Recovery Options. Follow this link and you'll see a section to download a boot media. https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186

Once you boot your pc from the media, click on repair your computer and you'll gain access to the Recovery Options menu.

**Comment by CasualSavage** [comment]
Hi,

Thanks for trying to help, but it doesn't work, I get to this screen and
from here my keyboard and mouse stop working, any ideas?

Thanks

On Friday, August 14, 2015, Bryan-Devenish notifications@github.com wrote:

> You can always try to use an installation boot media to get to the
> Recovery Options. Follow this link and you'll see a section to download a
> boot media. #186
> https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186
> 
> Once you boot your pc from the media, click on repair your computer and
> you'll gain access to the Recovery Options menu.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/191#issuecomment-130966806
> .

## 

Dylan

**Comment by CasualSavage** [comment]
It's the screen that displays different languages and at the stop says "Choose your keyboard style"

**Comment by Bryan-Devenish** [comment]
I'm not entirely sure, you'll have to take this up with the Windows forums with Microsoft. You're the first to have this much of an error. So i'm not entirely sure why your mouse and keyboard keep dying.

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
