### ISSUE TITLE
Login Screen is Broken 

### ISSUE THREAD

**Issue by dhaynespls** [PFCKrutonium/Windows-10-Login-Background-Changer#207]
System: Windows 10 Pro x64, w/ latest installed update KB3081438. Not on insider builds.
Application: 1.0.2

Hey,

I know you guys are getting flooded with these but I just want to add my experience to the list. I downloaded your application about like a half hour ago and attempted to change the wallpaper. Specifically, I used the "custom wallpaper" method at the top, loaded my pic, preview was good, and hit "apply changes". Prompted me to hit "lock windows" and upon so ran into the screen flickering issue which literally locked windows.

 It occurred when you swiped up or hit a key to remove the first screen into the second where it would lockup and prevent login like most everyone else has said. Followed the instructions off of the main thread about it and within 10 minutes was on here typing this. 

Again my experience is not unique just reporting the issue. If you need anything else let me know.

**Comment by chamtec** [comment]
Hi,
I have the same problem, I had to restore windows!

**Comment by dhaynespls** [comment]
@chamtec Oh man really? All you had to do was boot into recovery, get to the command prompt and cd your way to the backup/replace the corrupted login file. It's alright though as long as you fixed it no matter which way.

**Comment by Bryan-Devenish** [comment]
Follow this guide here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186

This will save you from losing personal files if you follow it correctly. Failing that it also has a back up step that you can use just in case things start looking bad. This method fixes the .bak corruption and allows you to install all windows update.

**Comment by seagull** [comment]
I just used RDP to connect to my machine and revert to defaults.
App is definitely busted, though.

**Comment by Toyz** [comment]
It's not the app it's Microsoft changing the Pri by mistake

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
