### ISSUE TITLE
Login Screen Broken on One Machine, Not the Other, Using Same Image, Version, Windows ISO

### ISSUE THREAD

**Issue by frankjunior** [PFCKrutonium/Windows-10-Login-Background-Changer#209]
Hello,
I am writing to report another case of the login screen being broken. I have already fixed the issue (so no need to respond with a "How to fix" guide, I am only reporting to help the development of this program). I have used your program on two of my systems: my laptop and my desktop. On my laptop, it was successful, even after the Windows updates. Still no issues with my laptop. On my desktop, however, I experienced the flashing issue using the same version of the program (1.0.2.0), the same image, and the same Windows 10 ISO. I have seen certain developers claim it is not the program's fault, but unfortunately, I do not think this is the case. Using Alphawaves's program found at http://forums.mydigitallife.info/threads/63920-Windows-10-Login-Lockscreen-Image-Changer-BETA?p=1094062&viewfull=1#post1094062 I have successfully changed my background on my desktop, again using the exact same image as before. I have even tested it on my laptop with the same results. I do not mean to attack your efforts, but your program is broken and a fix is needed.
Regards,
Frank

**Comment by melak47** [comment]
Hm, using the original powershell script I get the same flashing screen on my laptop.
Using this [updated version](http://forums.mydigitallife.info/threads/62367-Windows-10-Login-Screen-Background-Changer!-Uploaded-to-GitHub!/page61?p=1119434&highlight=#post1119434) though, using the same image, I get a working customized lock screen.
(The output .pri file seems to be the same size but I haven't compared further)

Edit: Sorry, need to login to see the link, so I'll post it here as well: http://pastebin.com/RkJW94ZA

**Comment by Toyz** [comment]
I will be converting that script to our built in pri editor the only issue is we have no way to know if your a gen1 or gen2 pri for example I'm prepatched to a gen1

**Comment by melak47** [comment]
@Toyz I created a fork and branched off of 1.0.2.0 [here](https://github.com/melak47/Windows-10-Login-Background-Changer/tree/bugfix/broken-login-screen), where I updated both the PriBuilder implementations.
It _seems_ to work reliably even for huge and detailed images that produce a 15MB - 25MB pri files,
but I don't know what the difference between gen1 and gen2 pri files is.

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
