### ISSUE TITLE
how is the command line option used?

### ISSUE THREAD

**Issue by rmusick** [PFCKrutonium/Windows-10-Login-Background-Changer#223]
When I try to do the following:
"W10 Logon BG Changer - Command Line.exe" /I C:\Windows\Web\Wallpaper\Windows\img0.jpg"
It returns the following error:
An error occurred: The file "" is not a valid file!

**Comment by KaleidonKep99** [comment]
You missed a quotation mark
The right command is:
`"W10 Logon BG Changer - Command Line.exe" /I "C:\Windows\Web\Wallpaper\Windows\img0.jpg"`

**Comment by tetra-fox** [comment]
Actually, it's `"W10 Logon BG Changer - Command Line.exe" /I"C:\Windows\Web\Wallpaper\Windows\img0.jpg"`

**Comment by emmatyping** [comment]
@Syrexide it shouldn't be. All other programs have a space between the switch `/I` and the parameter. If this truly is the way it works right now, we should change that.

**Comment by tetra-fox** [comment]
@IronManMark20 It is. It's just that while I was writing the command line version, I didn't know how to have it read the space but then ignore or remove it while processing the command. :stuck_out_tongue_winking_eye:

**Comment by emmatyping** [comment]
@rmusick, if you are experiencing further problems, then you can ask here.
