### ISSUE TITLE
Security Policies Login Loop

### ISSUE THREAD

**Issue by jansenfuller** [PFCKrutonium/Windows-10-Login-Background-Changer#226]
Changed the background as instructed in the readme. Now I can't login. I would enter in my password and be greeted by "Security policies on this computer are set to show the last interactive sign in but windows couldnt retrive that info. Please contact your network administrator for help." It then goes into an infinite loop. Every time I enter my password, that message shows up. Problem being its my personal computer at home that I built. I've tried going through the fixes but that just reset the image and not the login problem.

**Comment by jansenfuller** [comment]
Also, system restore and other recovery media options do not work.

**Comment by Krutonium** [comment]
This is an odd one, I don't think we _can_ cause this, but the evidence says otherwise...

@Toyz Is there a way in Windows 10 to force a username/password prompt like pressing CTRL+ALT+DEL on the login screen in XP?

http://depts.washington.edu/burkeit/wordpress/wp-content/uploads/2013/05/domlogin_xp.png
http://depts.washington.edu/burkeit/wordpress/wp-content/uploads/2013/05/domlogin_win7.png

If that is possible, then you just use your username/password to login, then we continue to work to a fix.

**Comment by jansenfuller** [comment]
I haven't tried that yet but for some reason, if I unplug my Ethernet cable and have no internet I can login but if I'm connected to the Internet, The "Security Policies" prompt shows up. I opened an issue because It happened after I used the app. It might/might not have been you.

**Comment by darth62969** [comment]
do you have you computer connected to a school or work account?

sometimes they like to mess with security policies especially if they interact with the servers on campus.

**Comment by jansenfuller** [comment]
It's a personal computer at my home. No one else is connected it to it besides my phone and other machines (2 to be exact)

**Comment by darth62969** [comment]
not what i meant... have you added a Work or School account, not joined it
to a domain. you can go to settings>accounts> add a work of school account.

(: Jonathan :)

**Comment by darth62969** [comment]
another thing, if you have it connected to some some other machines if one of them is a server like a home server, that could also be interfering, especially if it runs a network based security software. if that is the case i don't know what to do then, even though i have server at home it hardly runs when i am actually on the home network.

**Comment by darth62969** [comment]
@jansenfuller can you give us some more details on how have your network set up?

**Comment by darth62969** [comment]
i am going to go ahead an assume the issue has been resolved. if not please feel free to let us know, though i don't know if this was an issue with our program to begin with.
