### ISSUE TITLE
Windows.UI.Logon.pri.bak modify to Windows.UI.Logon.pri don't have lockscreen

### ISSUE THREAD

**Issue by cololi** [PFCKrutonium/Windows-10-Login-Background-Changer#227]
i wan't change login background again but my  Windows.UI.Logon.pri flie was delet....

**Comment by emmatyping** [comment]
I believe this is a duplicate of #197 . This is a Windows 10 feature, not a bug, If I recall correctly.
EDIT: nevermind, I don't think it is after all.

**Comment by emmatyping** [comment]
请仔细阅读本我们的wiki 

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login

（抱歉，但它是英文）

**Comment by emmatyping** [comment]
@kirito269 没能帮助？ (对不起，我不会说中国话)
Did that help? Sorry, I am sure you can see, I don't know Chinese. :wink:

**Comment by cololi** [comment]
no ,thank you ,i reinstall windows10 ,thank your help

**Comment by cololi** [comment]
@IronManMark20  thank you help me ,my english is not good
