### ISSUE TITLE
Typo in MainWindow.cs #77

### ISSUE THREAD

**Issue by FiatMortem** [PFCKrutonium/Windows-10-Login-Background-Changer#229]
Line #77 
LanguageLibrary.Language.Default.title_dg_disabled, MessageBoxButton.OK, MessageBoxImage.Information);'

title_dg_disabled should be title_bg_disabled.

Regards,
FM

**Comment by emmatyping** [comment]
Thank you for reporting this. This was already fixed in #220.

**Comment by FiatMortem** [comment]
OK sry, I was working off the source zip.

**Comment by emmatyping** [comment]
No problem. I would rather have you report it than not. :+1:
