### ISSUE TITLE
how to deinstall it?

### ISSUE THREAD

**Issue by kacke** [PFCKrutonium/Windows-10-Login-Background-Changer#236]
hello, I installed your Background-Changer but now I want to deinstall it. It´s not listed in the progamm-deinstalling list and in the folder I installed there is also no deinstall-function. 
Could you please help me with it?
Thank you!

**Comment by darth62969** [comment]
First the program does not install in the first place, but i will tell you how to revert its changes.

Click the restore defaults button within the program to revert changes. then if you must delete the program in its entirety.

**Comment by kacke** [comment]
Thanks for your answer and sorry for asking so stupidly (I just logged on here to get the problem solved): Is there no way to get the program away from my system completely? 
Didn´t I install it? Because it is there. :( It would be awesome if you could explain that to me (:

**Comment by darth62969** [comment]
like i said open the program. at the bottom on the edit background flyout
there is an option to revert everything, it is called "restore Defaults"
click that, then click OK on the window that appears. close the program and
delete it. make sure you also delete all of it's dll. if you extracted it
to its own folder this should be easy by just deleting the folder. after
that you just need to delete the zip the program came in. this will
completely erase its presence on your computer.

(: Jonathan :)

**Comment by kacke** [comment]
Haha, that was pretty easy, I already thought I had to do a lot of complicated stuff to erase it.
Thank you soo much, you helped me a lot!!!! And now I even know a little bit about ".exe"-programs :)

**Comment by darth62969** [comment]
your welcome, i am going to go ahead and close this but if you have any more questions or issues feel free to speak up.
