### ISSUE TITLE
Use of the program in a startup script

### ISSUE THREAD

**Issue by peterlouvel** [PFCKrutonium/Windows-10-Login-Background-Changer#237]
Hi, 

Great work on the program.

I'm trying to use this in a startup script

We use a startup script in Windows 7 replacing the logon screen image with an image that is created on the fly with date, time, computer name etc and trying to do the same with windows 10 but the program dosn't seem to work while running in a startup script.  it runs fine if I run the script manually while logged on. kind of stuck as to what the problem might be? the Windows.UI.Logon.pri has everyone set to full access.

---

ps:   c:\windows\bin\w10   is your program mentioned in the script below

---

strResolution = xRes & "x" & yRes
' convert is a program from iamgemagic to add images/text to existing images
strText = "cmd /c %windir%\bin\convert.exe %windir%\bin\WallPapers\background" & strResolution & ".jpg -font arial " 
strText = strText & "-pointsize 30 "
strText = strText & "-draw ""fill black text 200,100 'IP Address: " & QUT_Network_IP & "'"" "
strText = strText & "-draw ""fill black text 200,160 'Mac Address: " & QUT_Network_MAC & "'"" "

strText = strText & "-draw ""fill black text 200,220 'Staff Computer: " & strComputerName & "'"" "
strText = strText & "-draw ""fill black text 200,300 'Date: " & FormatDateTime(Date,1) & "'"" "
strText = strText & "-draw ""fill black text 200,360 'Time: " & Time & "'"" "

'Set the deploment date on wallpaper
strKeyPath = "SOFTWARE\Wow6432Node"
strValueName = "Deployment"
objRegistry.GetStringValue HKEY_LOCAL_MACHINE,strKeyPath, strValueName,strDeployment
strText = strText & "-pointsize 10 "
strText = strText & "-draw ""fill black text 50,20 '" & strDeployment & "'"" "

WshShell.Run(strText & " %windir%\bin\background.jpg"), Hidden, Wait_Yes
WshShell.Run("cmd /c %windir%\bin\convert.exe %windir%\bin\background.jpg null: -geometry +30+30 %windir%\bin\college.png -layers composite %windir%\bin\backgrounddefault.jpg"), Hidden, Wait_Yes

WshShell.Run("c:\windows\bin\w10 /Ic:\Windows\bin\backgrounddefault.jpg"), Hidden, Wait_Yes

' in windows 7 have to make the logonui restart to see the new image
Wshshell.run("cmd /c %windir%\system32\taskkill.exe /IM logonui.exe /F"), Hidden, Wait_Yes

---

ps : sorry about the big writing above. no idea why it's there.

**Edit (Darth62969)**: fixed it for you markup like to do that if you do not separate you lines. an additional line is needed between "----" and the line prior.

**Comment by emmatyping** [comment]
A startup script loads after you sign in. You would have to create a service to do anything earlier in the boot process.

**Comment by peterlouvel** [comment]
No, a logon script loads after you login, a statup script loads before the logon screen is displayed.
We have been using startup scripts back since XP days.

**Comment by Krutonium** [comment]
.Net applications can't run under system (Before login).

**Comment by peterlouvel** [comment]
ok  thanks  
https://jgiffard.wordpress.com/2012/02/03/dotnet-installation-gpo-startup-scripts/
this has something i'll look into for dot net in startup scripts, ill do some investigating next week.

**Comment by Krutonium** [comment]
That's for installing .Net 3.5, not using it.

**Comment by peterlouvel** [comment]
ok, got it working.
just have to have three files in the one directory together.

HelperLibrary.dll
SharedLibrary.dll
W10 Logon BG Changer - Command Line.exe 
   rename this to W10.exe

and your startup script has to kill the logonui.exe program BEFORE you run W10.exe 

Wshshell.run("cmd /c %windir%\system32\taskkill.exe /IM logonui.exe /F"), Hidden, Wait_Yes
WshShell.Run("c:\windows\bin\w10 /Ic:\Windows\bin\backgrounddefault.jpg"), Hidden, Wait_Yes

**Comment by emmatyping** [comment]
Cool! Thanks for sharing. I guess that solves your problem. :+1:
