### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by lirse** [PFCKrutonium/Windows-10-Login-Background-Changer#241]
My login screen is fully gray after using your software! I can not log in anymore! What do I do now... ?

**Comment by emmatyping** [comment]
This happens when the login program crashes. normally it would restart. Have you tried restarting your computer?

**Comment by lirse** [comment]
Almost turning it off, the same thing happens, see time, flashing between the gray screen that is loaded mine with three dots on the screen and lock screen.

 After restart again once I got this message between '' flashes '' screen:

"The exception to stop Point A breakpoint has been reached. (0x80000003) occurred in the application at the 0x00007FFB314A61AB location. Click OK to terminate the program."

But OK, it just continuously bugue ..

**Comment by Toyz** [comment]
Pris don't have a offset location this seems to be more related to Windows.UI.Logon.dll and looks like its corrutped I recommend booting into a command prompt and using a dism or sfc and repair the windows install

**Comment by lirse** [comment]
Finally, I was able to access the Windows Restore menu 10 by restarting the computer on and off 3 times, and I came back to the previous version of Windows, the restore point I created before upgrading to Windows 10.

**Comment by emmatyping** [comment]
please follow Toyz's advice. If you wish to re-open the issue, leave a comment.
