### ISSUE TITLE
Any chance or plans to include support for the Shut Down/Log out screens?

### ISSUE THREAD

**Issue by iSupremacy** [PFCKrutonium/Windows-10-Login-Background-Changer#242]
Unfortunately they're not affected by this application.

Thanks

**Comment by Toyz** [comment]
Those are not apart of any PRI there actually just a regtangel drawn by your selected color, cannot be a image (OS Limitation)

**Comment by iSupremacy** [comment]
Ah, isn't that a bumber.

**Comment by Toyz** [comment]
Kinda is but i mean we can edit the Logon screen more just takes us figuring out were the complied xaml is stored in the binary and then editing it by decompling the xaml

**Comment by emmatyping** [comment]
Closing, as we cannot do this feature. Sorry. :cry:
