### ISSUE TITLE
Error on selecting a file

### ISSUE THREAD

**Issue by JoelJordan** [PFCKrutonium/Windows-10-Login-Background-Changer#247]
When trying to select a file I get the error in the attached file. I also attached a log file. By the first try I used a path onto a server. It was accepted. Then I wanted to change the picture and I got the error.

![ff](https://cloud.githubusercontent.com/assets/14098242/9642045/4f55ce80-51ba-11e5-9711-c5244dba835a.jpg)
![log](https://cloud.githubusercontent.com/assets/14098242/9642070/79471f14-51ba-11e5-8ae0-3f60168632ae.JPG)

Regards,

Joël Jordan

**Comment by darth62969** [comment]
is the file you selected on a network location?

**Comment by JoelJordan** [comment]
yes

**Comment by JoelJordan** [comment]
But it crashes even before I can do anything.

JJ

**Comment by JoelJordan** [comment]
I meant, now after it was once successful.

JJ

From: Joël Jordan [mailto:joel.j.jordan@outlook.com] 
Sent: mercredi 2 septembre 2015 21:44
To: 'PFCKrutonium/Windows-10-Login-Background-Changer' reply@reply.github.com
Subject: RE: [Windows-10-Login-Background-Changer] Error on selecting a file (#247)

But it crashes even before I can do anything.

JJ

**Comment by darth62969** [comment]
are you running it from a network location?

**Comment by JoelJordan** [comment]
No, locally

**Comment by darth62969** [comment]
the log is cut off could you post it to pastebin?

http://pastebin.com/

**Comment by JoelJordan** [comment]
Et voilà

**Comment by darth62969** [comment]
link... we need the link to it....

**Comment by JoelJordan** [comment]
You mean http://pastebin.com/ZVPfN0ux

JJ

**Comment by emmatyping** [comment]
For those who don't know French:

La valeur n'est pas comprise dans la plage attendue = The value is not in the expected range

à = at

**Comment by Toyz** [comment]
This has been fixed it was cause of bad null value checking

**Comment by JoelJordan** [comment]
Hi there,

Thanks very much. Good to hear it. In which version is it going to be available and is it to download ?

Thanks,

Joël Jordan

**Comment by emmatyping** [comment]
I am not sure, @Toyz correct me if I'm wrong, but this isnt in a release yet.

**Comment by darth62969** [comment]
nope unless @PFCKrutonium builds one.

(: Jonathan :)

**Comment by Toyz** [comment]
Build it from source

**Comment by JoelJordan** [comment]
Sorry to disturb you again, but I am not a developper and I don’t know how to build. I can wait the next release. Is there any schedule ?

Regards,

Joël

**Comment by darth62969** [comment]
no, as far as we are concerned when the master decides to release we
release.

basically we have don't know when the next release will be, i think
releases should be regular but as long at it is not broken, we don't really
need to fix it. you can ask @PFCKrutonium to make a release i am sure he
will oblige.

(: Jonathan :)

**Comment by JoelJordan** [comment]
I would really appreciate because I cannot change the current configuration anymore.

Thanks for your support,

Joël
