### ISSUE TITLE
If there would be a tool to modify other .pri files

### ISSUE THREAD

**Issue by UlyssesWu** [PFCKrutonium/Windows-10-Login-Background-Changer#256]
I'm impressed by your analyzation of .pri file. And I just wonder how much you have known about this format. 
If we can parse and modify all those .pri files, maybe we can change other UIs of Windows10 and Windows apps.
(I know makepri.exe can dump .pri files, but there should be a replace function.)

**Comment by emmatyping** [comment]
Another complicating factor is that pri files only point to resources. XBF (compiled xaml) hold the actual UIs. We have thought about it. There are tools that have reverse-engineered xbf, pris could be figured out.

**Comment by UlyssesWu** [comment]
I see. MS provide a Xbf2Xaml function (all implemented in managed) in .NET Native (which used by XAML Decompiler <- it just have a few lines of code). XBF is not a problem i think. 

But I still can't find similar things for PRI. I find there are some clues in `AppxApplicabilityEngine.dll` (which have Microsoft::Resources::PriFile type) and `makepri.exe` (which have PriFileManager & PriFileMerger). But I'm unable to reverse them, and I can't find a way to call them (maybe it's impossible to call them without correct header files? ). I wish there would be a managed implementation... :<

**Comment by Toyz** [comment]
pris are compressed memory streams of the file contents scattered randomly on the pri you can view this by using makepri as it dumps the zero indexes of everything and nothing is in order and acctually making a editor i have already done but because pris are a closed source file type to MS basically i cannot release it of legal resions

**Comment by UlyssesWu** [comment]
Thanks for the information. In fact I think it's ok to release your tool and MS won't care.
