### ISSUE TITLE
Lock Screen is Broken

### ISSUE THREAD

**Issue by csmodfw** [PFCKrutonium/Windows-10-Login-Background-Changer#257]
After using Windows-10-Login-Background-Changer, Lock screen is fully gray for computer joined to domain, Login screen is changed like want it.

Dism /Online /Cleanup-Image /RestoreHealth 
(p) CSI Payload Corrupt (Fixed) amd64_microsoft-windows-ui-logon-library_31bf3856ad364e35_10.0.10240.16431_none_8550a5f8e3899879\Windows.UI.Logon.pri

Summary:
Operation: Detect and Repair 
Operation result: 0x0
Last Successful Step: Entire operation completes.
Total Detected Corruption:  1
    CBS Manifest Corruption:    0
    CBS Metadata Corruption:    0
    CSI Manifest Corruption:    0
    CSI Metadata Corruption:    0
    CSI Payload Corruption: 1
Total Repaired Corruption:  1
    CBS Manifest Repaired:  0
    CSI Manifest Repaired:  0
    CSI Payload Repaired:   1
    CSI Store Metadata refreshed:   True

fixed, but also revert wanted changes of login screen.

**Comment by Krutonium** [comment]
That file is what we edit to inject new backgrounds, so of course it will show up as corrupted. As for the corrupted background image, download the PRI that is around here somewhere, drop it in and patch it instead and it will work better.

**Comment by csmodfw** [comment]
This not help if computer is joined to domain.
When computer is locked(WIN+L) is don't show lock screen, is just gray. When is press CTRL+ALT+DEL to unlock is show modified login screen, this bug not affected computer not joined to domain. Running RestoreHealth is revert back to blue login screen and WORKING lock screen. Please not make confusion are taking about lock screen not work and not login screen.

**Comment by darth62969** [comment]
that may be a windows 10 issue and not us, i would suggest popping a issue in to the windows feedback app, as i don't think there is much we can do. we don't do anything for the lock screen. we only modify one PRI to change the login screen. if windows has an issue with this when we can't do anything about it. only MS can, not that they likely would.

**Comment by csmodfw** [comment]
Close, windows build 10.0.10586.3, not have this error.
