### ISSUE TITLE
Command Line Syntax Borked?

### ISSUE THREAD

**Issue by BuckRogers25** [PFCKrutonium/Windows-10-Login-Background-Changer#259]
Hi there,

Had the same run error as https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/258 , so decided to try command line, only looks like the syntax is off.

![capture](https://cloud.githubusercontent.com/assets/10714993/9834493/585d928c-59b3-11e5-8673-c04074458ad4.PNG)
Am I just being incredibly dense ? :)

**Comment by emmatyping** [comment]
Well, first off (and this doesn't fix your problem), you should run `"W10 Logon BG Changer - Command Line.exe" /C000000` I can reproduce this, which means you should probably build from source.

**Comment by BuckRogers25** [comment]
"W10 Logon BG Changer - Command Line.exe" /C#000000 did it, success message, but still no joy as to actually setting the color.

I'll grab the source :).

**Comment by emmatyping** [comment]
Re-open if you have problems with that. :smiley:

**Comment by sejalivre** [comment]
"W10 Logon BG Changer - Command Line.exe" /i ???

dont work....
