### ISSUE TITLE
"Show information" option not work for hidden info

### ISSUE THREAD

**Issue by KrAzYtHeBoY** [PFCKrutonium/Windows-10-Login-Background-Changer#260]
Turn OFF "Show information" option for hidden user avatar and email.. not work. Use 1.2.0.0 Win10 Retail x64

please fix it... thanks

**Comment by Toyz** [comment]
This is a Application feature,  there is no way to actually turn that information off without physically editing the xaml which is almost impossible currently 
On Sep 14, 2015 7:46 AM, KrAzYtHeBoY notifications@github.com wrote:Turn OFF "Show information" option for hidden user avatar and email.. not work. Use 1.2.0.0 Win10 Retail x64

please fix it... thanks

**Comment by KrAzYtHeBoY** [comment]
Thanks, manual mode not disable avatar/email?

**Comment by Toyz** [comment]
There is currently no way to actually disable the info in the pri

**Comment by emmatyping** [comment]
See label

**Comment by Miguel767** [comment]
what do you mean with See Label?
will it not work?

**Comment by emmatyping** [comment]
Yes. It won't happen.

The login screen has a binary part that we cannot edit, which contains this information.
