### ISSUE TITLE
Spanish Translation v1.0 AVAILABLE

### ISSUE THREAD

**Issue by KrAzYtHeBoY** [PFCKrutonium/Windows-10-Login-Background-Changer#261]
http://pastebin.com/nigqUZ0U

**Comment by Krutonium** [comment]
@Toyz

**Comment by emmatyping** [comment]
@KrAzYtHeBoY can you do it based on the most recent en_US.xml please?

[link](https://gist.github.com/IronManMark20/ccf0553f45138359b975)

**Comment by KrAzYtHeBoY** [comment]
@IronManMark20 @PFCKrutonium @Toyz update spanish lang.

view on = http://pastebin.com/nigqUZ0U

thanks

**Comment by emmatyping** [comment]
This should be merged, so I am closing. :)
