### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by ccodykid** [PFCKrutonium/Windows-10-Login-Background-Changer#264]
Image: http://tammypain.deviantart.com/art/Ore-Twintails-ni-Narimasu-Wallpaper-489436513
PC Specs: 
Windows 10 RTM latest Update
i7 3770K 4.4Ghz OCed
nVidia GTX970
16 GB RAM
265 GB SSD + 4,5TB HDD
Creative Soundblaster Z
# PCMasterRace

Win10BGChanger Version 1.2.0.0
No other custimization tool, avast antivirus

My logon screen turned grey and only my mouse is visible. It didn't work obviously. Hope you can help. Many thanks.

**Comment by darth62969** [comment]
can you login? is it flashing?

**Comment by ccodykid** [comment]
No, I can't log in nor is it flashing. I just get a plain grey screen and I can move my mouse, that's all.

**Comment by darth62969** [comment]
it works with avast for me, what tools do you have installed with it?

**Comment by ccodykid** [comment]
I had avast deactivated. I have no tools installed or whatsoever. I just can't figure out why it doesn't work...

**Comment by darth62969** [comment]
i did a basic install and disabled everything in the install except the bear essentials. so it seems to not be avast as it is working. (even with it enabled.) so i have no idea.

@Toyz do you have anything to add?

**Comment by ccodykid** [comment]
Strange thing is command line doesnt work now. It just flashes and disappear.

**Comment by darth62969** [comment]
wait is that when you try to revert the pri?

**Comment by ccodykid** [comment]
No no no. I mean the W10 Logon BG Changer - Command Line coming in the .zip file.

**Comment by darth62969** [comment]
that is cause you have to run it via an admin command prompt, and i thought you said you could not login... or did you revert then try the command line...

**Comment by ccodykid** [comment]
Yes, I revert it back and try the command line

**Comment by ccodykid** [comment]
Nothing changes as I tried to run it as admin.

**Comment by darth62969** [comment]
ok so like i said the commandline version you have to run form an admin commandprompt go to file> open command prompt>open admin command prompt

then run it as shown in the wiki.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Command-Line

**Comment by ccodykid** [comment]
Not working. I just dont know...

**Comment by Toyz** [comment]
try using the GUI version? if you can't solve how to open CMD as admin i recommend using the GUI version which uses a easy to understand interface.

I have yet to be able to recreate this issue on 5 different hyper-v instances of Windows 10 builds 10247 to 10547

**Comment by ccodykid** [comment]
I did try it with the GUI Version, but it also doesn't work. It seems to doesn't work at all. Geez I don't know anymore...

**edit (darth62969):** removed excess junk from email client

**Comment by ccodykid** [comment]
Just some information: I am on Windows build 10240 and there are several people on different forums having the same problem on the same build. Can you relate?

**Comment by emmatyping** [comment]
I too am on 10240, and have tested it multiple times, yet it works fine. I dont think it is the build number.

**Comment by ccodykid** [comment]
On my notebook (Windows 10 build 10240) this works just fine. I don't really know, what problem my pc has. Maybe I just have to do a clean install of Windows 10 since I just updatet it through that upgrade tool thingy. I'll give it a try this evening!

**Comment by ccodykid** [comment]
Thank you for all your kind help!

I clean installed Windows 10 and look at that: It works perfectly now! 
I don't know how many actually upgrade their Windows, but it doesn't seem to work with the upgraded "version".

**Comment by darth62969** [comment]
it seems like this issue has been resolved. i am going to go ahead and close it then.
