### ISSUE TITLE
Blacked out system icons

### ISSUE THREAD

**Issue by therockers** [PFCKrutonium/Windows-10-Login-Background-Changer#267]
Having a new clean installation and using Windows 10 Login Background Changer does this. System icons were blacked out when I hit the apply button. This was on a new installed Windows 10. Not an upgraded version from Windows 7 nor 8.

![black_icons](https://cloud.githubusercontent.com/assets/2050490/10568024/f50bd900-75d7-11e5-9212-fbced465ac04.png)

**Comment by emmatyping** [comment]
I do not believe that our program could cause this directly, however, you should be able to fix this by resetting your icon cache.

**Comment by therockers** [comment]
Those icons were normal before I did anything with the Windows Login Screen Changer. I've been looking at my "My Computer" folder every 5 minutes for the past 16 hours and it wasn't like that until I decided that I wanted to change my logon screen. I didn't install anything prior nor did I install anything after. It was after when I had changed my screen when I went to browse my folders that I had seen blacked out icons. I restarted my computer just in case, but they aren't going away.

Maybe with each different build, there's a different problem. I don't know. I have the Insider's Pro edition. Clean install too.

**Comment by darth62969** [comment]
i can guarantee this is not the app, but i will suggest you follow @IronManMark20's advice and reset your icon cache, he SHOULD provide a link to help you with that. 

"but this happened immediately after i used the app"
that may be so, but the app does not change anything out side of the logon UI specifically ONE file attributed to that. we do not change or mess with anything out side of that one file, and the file does not mess with any of your user file icons. this is most likely windows being a derp and can be fixed but doing what was suggested above. otherwise you can try fix it using the steps outlined in the wiki. 

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login

or you can follow my video tutorial on the issue.

https://www.youtube.com/watch?v=J79ihzOKQLU

note if it was out app that screwed up you would be looking at something like this and not something like you are experiencing.

**Comment by therockers** [comment]
Already tried clearing the cache. Nothing changed.
Used this link too to clear the cache. http://www.tenforums.com/tutorials/5645-icon-cache-rebuild-windows-10-a.html

:/ This is why I dislike Windows. Windows has the most problems out of all of the distributed OS. Sometimes, Windows gets bricked after the first 2 seconds it gets turned on. This is why I like Linux more, but I can't play my games on Linux so I have to deal with sh...y Windows.

**Comment by darth62969** [comment]
i can't tell you how many times i have had a linux distro that screwed up 2 seconds after install. actually my luck has been just the opposite. i can never get linux to work quite right. while with windows, i have run into far less issues... granted i had to reinstall Linux 2-6 times in the few months before i got windows 7, and i had windows 7 for 4 or 5 years and reinstalled it 5 or 6 times. the longest of installs lasted over a year before i gummed and cocked up... and i was forced to pretty much flatten the install.

**Comment by therockers** [comment]
Going off-topic now, but for me. For some reason, either Windows doesn't like me or I just have bad luck with Windows because when I tried to install a few updates on the home computer so that Windows is optimized. It basically froze at like 13% so I had to turn it off no matter what. Then it broke. Had to do system restore on it to get it back. Then on my personal computer. When I was trying to install Windows 8.1, the screen was too wide and it didn't have any good resolution options so I remember I had old drivers from Windows 7. I remember that I had attempted to do the same on my Windows 10 Technical Preview and the screen adjusted itself after the drivers updated. So I attempted to do the same with Windows 8.1. Poof, bricked my BIOS. Had a broken computer that I had to wait to get fixed. Had to buy a new motherboard. For Linux, none of that happened because if Linux screen was too wide, it'll adjust itself.

But back to the topic. I'll just live with it I guess. I don't want to brick my computer again.

**Comment by Krutonium** [comment]
As someone who has worked extensively on modifying Video Card Drivers, I'm calling bullshit on a Video Driver bricking your BIOS.

As for above, what they said is true - there is no way we directly caused the issues with your icons.

And I have found Linux and Windows equally stable.

**Comment by therockers** [comment]
@PFCKrutonium It wasn't a video card. It was resolution (graphic). Not video. I used old drivers for Windows 7 and one of the drivers updates the BIOS. That is the only way that the resolution back then for me was fixed. Because when I update the BIOS, the BIOS then updates the graphics resolution. It turns the crappy Generic PNP monitor to an updated Windows monitor which has more options and has the right resolutions. I've tried it on Windows 7, Windows 8 (not 8.1 nor pro), and Windows 10 Technical Preview. They all updated without a problem.

I might just have to backup my files and rebuild the Windows partition again. The first app I'm going to try is the Windows Logon Screen Changer. If the icons are normal from a new installation and if the Windows Logon Screen Changer is the first and only app I will test on the new installation and if it changes the icons. I'll let you guys know. If it doesn't, I'll still let you guys know. This could be a bug.

**Comment by Krutonium** [comment]
If it is, then thanks for reporting it, otherwise, thanks for checking :D

**Comment by therockers** [comment]
@PFCKrutonium Ok, so it looks like it isn't the Windows Logon Screen Changer. Might be something else. The last program I installed before touching the Windows Logon Screen Changer was pcsx2-r5875 (PS2 emulator). Maybe that was the cause, but I installed it the day before. Maybe it didn't take into affect until I restarted my PC.

Sorry for blaming it on you guys.

**Comment by emmatyping** [comment]
@therockers no prob. Also, several people have been reporting that same problem on forums I frequent, but I don't know why re-settting you cache isn't working. I dunno.

**Comment by Krutonium** [comment]
:)
