### ISSUE TITLE
How do you bring the settings back up after you restart your laptop

### ISSUE THREAD

**Issue by jckinnick** [PFCKrutonium/Windows-10-Login-Background-Changer#269]
I want to change my background picture again, but where are the settings?

**Comment by Krutonium** [comment]
What do you mean? When you open the program, it should show them right from the beginning.

**Comment by jckinnick** [comment]
Where is the program? My background changed when I installed it, but there is no program on my computer that I can find.

**Comment by Toyz** [comment]
The program doesn't install there is no actual installer for the program, it would be in the same place you extracted the zip from usally in your "Downloads" folder

**Comment by jckinnick** [comment]
I think I deleted that. Can I download it again from github and get it to work?

**Comment by emmatyping** [comment]
You can always re-download the program. When you download it, it comes in a zip file `Win10BGChanger1.2.0.0.zip`, so I recommend looking for that. Also, if that doesn't exist, just re-download it.

**Comment by emmatyping** [comment]
@jckinnick did that solve your problem?

**Comment by jckinnick** [comment]
Maybe, the program was installed on my other laptop. I will let you know when Im on that laptop again.

**Comment by darth62969** [comment]
this has been open over a month and has not shown any activity from the user asking for help. i am going to go ahead on close this.
