### ISSUE TITLE
"Show Glyphs" not working

### ISSUE THREAD

**Issue by BirgitBleier** [PFCKrutonium/Windows-10-Login-Background-Changer#274]
Hi,
I am using latest version on Windows 10. Everything works out fine for me except the "Show Glyphs" option. No matter if activated or not the "ease of access", "connect to internet" and the power button won't vanish.

It this a known problem?
Windows 10, German Edition.
Thanks,
Birgit

**Comment by My1** [comment]
if you have pro then you can disable shutdown without login in gpedit as well.

**Comment by tetra-fox** [comment]
That switch is just for the program's preview area. They don't actually function to make them hide on the login screen. You may try @My1's solution though.
