### ISSUE TITLE
error  by starting

### ISSUE THREAD

**Issue by Hefaistos-NL** [PFCKrutonium/Windows-10-Login-Background-Changer#277]
### W10_Logon_BG_Changer Crash

De aanroep van de constructor in type W10_Logon_BG_Changer.MainWindow dat overeenkomt met de opgegeven bindingsbeperkingen, heeft een uitzondering veroorzaakt.
System.Dynamic.ExpandoObject bevat geen definitie voor title_dg_disabled
   bij System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bij System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bij System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bij System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   bij System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   bij System.Windows.Application.DoStartup()
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bij System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bij System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Windows.Threading.DispatcherOperation.Invoke()
   bij System.Windows.Threading.Dispatcher.ProcessQueue()
   bij System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bij System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bij MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bij MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bij System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bij System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bij System.Windows.Application.RunDispatcher(Object ignore)
   bij System.Windows.Application.RunInternal(Window window)
   bij System.Windows.Application.Run(Window window)
   bij W10_Logon_BG_Changer.App.Main()

**Comment by darth62969** [comment]
dublicate, already fixed in the development build...

enable the logon background in the registry.

(: Jonathan :)

2016-01-05 8:05 GMT-05:00 Hefaistos-NL notifications@github.com:

**Comment by Hefaistos-NL** [comment]
thats fast  gonna try it

**Comment by Hefaistos-NL** [comment]
HKEY_LOCAL_MACHINE\ Software\ Policies \ Microsoft \Windows \ System\ UseOEMBackground  =1
Still error .

**Comment by Hefaistos-NL** [comment]
version 1.0.2.0 hase no error  but no change of login screen

**Comment by darth62969** [comment]
that should screw up your system.... 

https://www.youtube.com/watch?v=J79ihzOKQLU

like i said you need to do the inverse of this

https://hellpc.wordpress.com/2015/10/06/how-to-disable-logon-screen-background-image-in-windows-10/

this feature was implemented in case users in an enterprise environment have had the background disabled by IT in order to prevent unauthorized changes to the system. though not fool proof, it does work against the common user. obviously IT would know how to get around it. it is obvious bugged because of the typo but, it has the same effect. we also need to release a new release with the fix for this.

**Comment by Hefaistos-NL** [comment]
ok thanks

**Comment by Hefaistos-NL** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\DisableLogonBackgroundImage =1  must be 0  than it works.
thanks for your help

**Comment by darth62969** [comment]
your welcome.
