### ISSUE TITLE
I need help, i cant use my pc

### ISSUE THREAD

**Issue by ConnorMLP** [PFCKrutonium/Windows-10-Login-Background-Changer#279]
Sorry for my english
I just installed your program to change my login background and, when i did and click to try it my screen starts to blink, to make flashes, my lock screen appears occasionally but i cant login, i cant do anything anf i need my pc :(

**Comment by darth62969** [comment]
oh hell

https://www.youtube.com/watch?v=J79ihzOKQLU

get the latest update.

(: Jonathan :)

**Comment by ConnorMLP** [comment]
Thanks!! :D

**Comment by emmatyping** [comment]
Closing as this seems resolved.
