### ISSUE TITLE
Hi, I'm dumb. I need help please.

### ISSUE THREAD

**Issue by teensupreme** [PFCKrutonium/Windows-10-Login-Background-Changer#282]
Soooooooo which file(s) am I supposed to be downloading exactly? The "master" by clicking on the "Download ZIP" button found on this page...
![imgchanger2](https://cloud.githubusercontent.com/assets/17020385/12742129/c4839a94-c937-11e5-9632-8601dfb39b1b.png)

or do I download each of the following three files found on this page...
![imgchanger1](https://cloud.githubusercontent.com/assets/17020385/12742147/ec94b018-c937-11e5-8456-c4669fa8c741.png)

And during the extraction process, when asked whether or not I would like to replace the existing files with these new files, do I select "No to all", "Yes to all".....?

**Comment by My1** [comment]
you better let it be. this thing can really crash your computer, even for people who are not as dumb as you.

**Comment by Krutonium** [comment]
> can really crash your computer

I mean, your not wrong, but its a rather easy thing to fix, and that was rather rude. @teensupreme You want the Win10BGChanger1.2.0.0.zip

**Comment by My1** [comment]
he literally said he is dumb himself, and I just used that as base.

**Comment by Krutonium** [comment]
Still rude either way.

**Comment by teensupreme** [comment]
Thanks for the advice! I'll try out that file and let you know how it goes.

**Comment by emmatyping** [comment]
@teensupreme , did that work?

**Comment by emmatyping** [comment]
@teensupreme if you are having further issues, please either respond here or file a new one.
