### ISSUE TITLE
background changer giving error message after i reformatted computer old wallpaper cannot be changed

### ISSUE THREAD

**Issue by mashedbr0tat0** [PFCKrutonium/Windows-10-Login-Background-Changer#288]
Please make sure these are checked so we can help you! (put an x in the [ ] to check it)
- [ X] I am running Windows 10, from build 10240 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
- [ X] I am running the program as administrator

If you are using the command line, please give us the full traceback (any output that include errors you have), or an image of the traceback.

If you are using the GUI version, please make sure you can check this:
- [X ] I have the setting "Show Windows background picture on the sign-in screen" set to on (it is in Personalization->Lock Screen)

Also, please send a screen shot of any error dialog that may show up for the GUI version.

Finally, please provide any other information that you feel is relevant.
I had to reset my computer because of a virus after doing so every time I try to use the background changer it gives me the error "there was an error while executing this application and will be shutdown" it keeps showing the background I used before I reset the computer. any help would be great thanks
![capture](https://cloud.githubusercontent.com/assets/17420078/13239062/a199739a-d9a5-11e5-8c68-f80dc9adb675.JPG)
"

**Comment by Toyz** [comment]
There should be a error file it genorated whats in the error

**Comment by mashedbr0tat0** [comment]
where would the error file be located

**Comment by mashedbr0tat0** [comment]
I found that file its a long readme file at the top
the top most message was
Not compatible with this PRI file

**Comment by Toyz** [comment]
thats a werid bug cause if your pri version is not the exact version or prevoulsy modifyed we can't modify it you need to download the pri from the link on the readme and use that one

**Comment by mashedbr0tat0** [comment]
I'd like to try that but there isn't a link at all in the readme file

**Comment by Toyz** [comment]
@PFCKrutonium wheres the link D:

**Comment by mashedbr0tat0** [comment]
I have no idea and at my wit's end, thanks very much for your help though

**Comment by darth62969** [comment]
https://github.com/angelkyo/Windows-10-Login-Background-Changer/releases/download/zh_CN_1.1.0.0/Windows.UI.Logon.pri.bak.7z

^^ there at the bottom

**Comment by bjsvedin** [comment]
So i have the same problem, but i don't know what to do with that file.

**Comment by emmatyping** [comment]
@mashedbr0tat0 if you are still having issues, let us know, otherwise, this seems to be solved.
