### ISSUE TITLE
It's stuck

### ISSUE THREAD

**Issue by Ashisnotacat** [PFCKrutonium/Windows-10-Login-Background-Changer#289]
Please make sure these are checked so we can help you! (put an x in the [ ] to check it)
- [x] I am running Windows 10, from build 10586 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
- [ ] I am running the program as administrator

If you are using the command line, please give us the full traceback (any output that include errors you have), or an image of the traceback.

If you are using the GUI version, please make sure you can check this:
- [ ] I have the setting "Show Windows background picture on the sign-in screen" set to on (it is in Personalization->Lock Screen)

Also, please send a screen shot of any error dialog that may show up for the GUI version.

Finally, please provide any other information that you feel is relevant.

The sign-in screen changed to a dark blue when I clicked a link given in the website. (https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer)
The screen did not change when I ran the file and chose a different color. I don't know why this is happening or how to fix it.

**Comment by emmatyping** [comment]
You need to run the program as administrator... otherwise it won't work.

**Comment by emmatyping** [comment]
So, unless you want to give more information, I cannot help you. I am closing this as invalid, but if you would like to reopen it, leave a comment and I would be happy to issues with this program you encounter.
