### ISSUE TITLE
Is there a way to change the wallpaper without this software?

### ISSUE THREAD

**Issue by aloisdg** [PFCKrutonium/Windows-10-Login-Background-Changer#298]
- [x] I am running Windows 10, from build 10240 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
- [x] I am running the program as administrator

Hello,

Everything works as expected. No problem for here on 10586.
You said that this software is obsolete. Is it still true?

> If you are on 14279 or later, please use the built in tool in the settings

Which tool are you talking about?

**Comment by Toyz** [comment]
In settings your lock screen picture is now your background on the login screen

![image](https://cloud.githubusercontent.com/assets/1471840/15414283/0dd97910-1dee-11e6-93fb-6c7d0c2f6249.png)

**Comment by aloisdg** [comment]
@Toyz I dont have this option. What version are you running? I am running the 10.0.10586 which is, afaik, the last one.

![theme](https://cloud.githubusercontent.com/assets/3449303/15414350/215dce86-1e3a-11e6-89fc-8fc66db301c9.PNG)

**Comment by darth62969** [comment]
@toyz in ot the latest insider preview... you are on release so...

(: Jonathan :)

**Comment by aloisdg** [comment]
@darth62969 So @Toyz is ahead with a sid/beta/whatever version of Windows10?

**Comment by Toyz** [comment]
If your on a public release build not a insider builder the tool will do it but in the insider builds the tool no longer works cause the PRI was completely changed to point to a registry value with a encrypted type of the first file in the selected images for lock screen

**Comment by aloisdg** [comment]
@Toyz I guess I have my answer. Thank you.
