### ISSUE TITLE
Microsoft defender indetifies this as a trojan

### ISSUE THREAD

**Issue by darth62969** [PFCKrutonium/Windows-10-Login-Background-Changer#3]
don't know what the issue is but i downloaded this and defender went off when i wanted to run this as admin (because permissions issues). don't know what exactly happened but... timing is a little weird.

i don't think this is but, you can never be too carful

also here is the link i got from MS defender with some more details.

http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fHiclas.A!plock&threatid=-2147271996&enterprise=0#tab=1

**Comment by Krutonium** [comment]
False Positive. Check the source if your worried :)

**Comment by darth62969** [comment]
ok first things first you don't close this as soon as you find out that it is being identified as a trojan. second thing is that, you try to figure out why it is being detected as such. 

i have no doubt there is nothing to be concerned about but you are making me less likely to use it, because of how you are handling it. do some research and fix it. don't just pass it off as a false positive.

**Comment by Krutonium** [comment]
1) Fine I'll re open it.
2) I know why it is being detected as a Trojan; It is modifying and patching Windows Files, which many viruses/trojans are want to do.
3) How would you propose we fix it? There really isn't one. I've fought this battle before with another project.

**Comment by darth62969** [comment]
i know windowsblinds runs a client... but i don't know if that would work in this application... if there is a registry entry that can change it that way. that is how something like this worked in 7. 

here is a thread i created on technet to try to solve this problem with the registry. 
<a href="https://social.technet.microsoft.com/Forums/en-US/b2afdb3a-b654-4c3d-a95f-866affc6d50c/windows-10-login-screen-how-do-i-get-rid-of-the-windows-10-wallpaper?forum=win10itprosetup#b2afdb3a-b654-4c3d-a95f-866affc6d50c">here </a>
as the windows 7 trick did not work, i don't know how we can do it otherwise. if you can submit the program to Norton and MS, have them evaluate it, and give it a greenlight/tips on how to make it work better, that is another option. 

but i would also make sure you back up any files you change, to ensure that you can reset everything.

**Comment by Krutonium** [comment]
A client like WindowsBlinds wouldn't work in this case

There isn't a registry entry we can change the change the background, we have to patch a pri file.

Norton... Just... No... And Microsoft never responds to things like this.

Also, a backup is made when you run it (assuming it can get permissions). Which is the current issue.

**Comment by darth62969** [comment]
the lack of permissions, may spawn from the false positive. i tried giving them to it, and that is when it gave me the Trojan issue.

**Comment by dambrisco** [comment]
Defender most likely identifies the Windows paths in the executable and throws a fit - there's no "legitimate" reason for a program to modify anything under C:\WINDOWS.

However, you could get a certificate through [Authenticode](https://msdn.microsoft.com/en-us/library/ms537361%28v=VS.85%29.aspx) to sign the executable with which _might_ prevent the error, but anyone is equally able to just compile the source on their own machine to avoid the "unknown publisher/developer" screen.

**Comment by Krutonium** [comment]
Or we could acquire a certificate to sign releases.

**Comment by Krutonium** [comment]
Well, releases are now signed - can I close this now?

**Comment by darth62969** [comment]
yes you can, but i got a new issue...

**Comment by The-Exnor** [comment]
Of topic but thanks for this program :)
