### ISSUE TITLE
"restore defaults" doesn't work.

### ISSUE THREAD

**Issue by pppop** [PFCKrutonium/Windows-10-Login-Background-Changer#302]
Please make sure these are checked so we can help you! (put an x in the [ ] to check it)
- [x] I am running Windows 10, from build 10240 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
  >> I am currently running **build 10584.164**
- [x] I am running the program as administrator
  >> I do
  If you are using the command line, please give us the full traceback (any output that include errors you have), or an image of the traceback.

If you are using the GUI version, please make sure you can check this:
- [x] I have the setting "Show Windows background picture on the sign-in screen" set to on (it is in Personalization->Lock Screen)
  >> I do

Also, please send a screen shot of any error dialog that may show up for the GUI version.

Finally, please provide any other information that you feel is relevant.
# 

First of all since I am not English native so you may not understand some of my writing. Sorry about that.
I wanted to uninstall the program and I found someone who had the same issue (https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/236) 
so I followed the advice. However in my case, it didn't work at all. 

whenever I click "restore defaults" and try to apply the change
the pop-up appear which said 'I have to select the file'
![error](https://cloud.githubusercontent.com/assets/22014029/18257289/1c478e60-73fc-11e6-8401-8da6cdc953e0.jpg)
(you said the 'restore defaults' also regarded as A file, but I think it does not work properly)

I even reinstall the window, but I was not able to restore the defaults setting of window.
**Is there any way I can restore the dafault setting of Window?** I desperately need help.
Any advice will be appreciated. Thanks.

**Comment by darth62969** [comment]
@PFCKrutonium does the program restore defaults from the .bak file? i would
assume so, so if they don't have that file then wouldn't that mean they
can't restore defaults?

(: Jonathan :)

**Comment by pppop** [comment]
Well... I am not sure about that... you mean the program automatically save the default as .bak file?

**Comment by darth62969** [comment]
yes when you run the program it should save the default unmodified pri as a
pri.bak file. all the restore defaults should do is copy that file inplace
of the modified PRI, if you make any changes to what you have set this file
is also used to make the changes. if this file doesn't exist i can see an
issue like this coming up.

(: Jonathan :)

**Comment by pppop** [comment]
SO IF MY LAPTOP DOES NOT HAVE .BAK FILE, THERE IS NO WAY I CAN  FIX THE  PROBLEM??? OMG....

**Comment by darth62969** [comment]
download the one in the README.md and follow the insructions here:
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login

for the .bak
https://github.com/angelkyo/Windows-10-Login-Background-Changer/releases/download/zh_CN_1.1.0.0/Windows.UI.Logon.pri.bak.7z

(: Jonathan :)

**Comment by pppop** [comment]
First of all, thank you soooooooooooo much for your kind advice.
Before I follow the 'README' instruction,
I tried **'restore hero'** option in 'Windows.10.Background.Changer' to fix the problem
And fortunately  it seems like the problem has fixed, but since I didn't have such opiton in new release (which is 'Win10BGChanger1.2.1') I am not sure if the problem fixed properly. 
Do you have any idea about this option (restore hero)?

**Comment by darth62969** [comment]
same as restore defaults to my knowledge. though they may work a bit
differently.

(: Jonathan :)

**Comment by pppop** [comment]
Oh... I see! then I guess my problem has been solved! MUCH appreciate for your help and hope you have a great day(or night!) ;D
