### ISSUE TITLE
DO NOT USE THIS APP - loggin impossible

### ISSUE THREAD

**Issue by WakeDown-M** [PFCKrutonium/Windows-10-Login-Background-Changer#306]
After changing bacground image i can see only black screen with the mouse - no possibility to enter pwd. I will be forced to reinstall whole pc. Do not use this lame app.

**Comment by Toyz** [comment]
If you read the readme.md file we deprecated this program and it no longer supported as windows added the support natively

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by emmatyping** [comment]
Also you don't need to re-install see https://github.com/Krutonium/Windows-10-Login-Background-Changer/issues/186

**Comment by WakeDown-M** [comment]
Hmm problem is, that I cannot log in. I see just black screen and mouse cursor. Even I load to safe mode or safe mode with command prompt I get to same state but resolution is just lower. No possibility to enter any win menu. I can try to boot linux and locate bak files. What is worse is that there is no troubleshooting option on my win installation so I cannot access to WIN at all.

**Comment by emmatyping** [comment]
I'd suggest booting linux or off of a windows install disk. That way you can use the bak file.
