### ISSUE TITLE
Controls overlap when resizing 

### ISSUE THREAD

**Issue by SamKimbinyi** [PFCKrutonium/Windows-10-Login-Background-Changer#38]
When the MainForm is resized vertically the controls in the Background Settings flyout overlap 
eachother

![Image of Form](http://i.imgur.com/WhbdGBD.png)

**Comment by Toyz** [comment]
Will fix there is no min size that's why, this will be patched

**Comment by tetra-fox** [comment]
Fixed in 9fcc439
