### ISSUE TITLE
Supplement Transparent PNG

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/Windows-10-Login-Background-Changer#58]
With this:

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System]
"DisableLogonBackgroundImage"=dword:00000001

**Comment by Toyz** [comment]
Not really needed as the transparent PNG is actually a faster loading time but we can add this as more of a admin side feature for server admins

**Comment by Krutonium** [comment]
Fair enough, lets do that then

**Comment by Toyz** [comment]
We will do it in a coming build right now working on some werid memory issues in the program that cause a random memory spike, but we will get it added sooon theres already a helper.cs now to do basic checking of it
