### ISSUE TITLE
if "DisableLogonBackgroundImage" is enabled in regenstry changes do not take effect.

### ISSUE THREAD

**Issue by darth62969** [PFCKrutonium/Windows-10-Login-Background-Changer#67]
![image](http://i.imgur.com/0iVROuj.png)

So if this setting in regedit is enabled the program does not work, lets keep it this way, but we probably need to let people know that is is preventing changes. Changes are completed successfully but they are not seen. This would be good if lets say a company does not want people to change the system, specifically the lockscreen BG, but you have admin rights.

The location of this setting is as follows.

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System

It is a D-Word and value is 1 if enabled and 0 of disabled.

This setting disables everything.

**Comment by Toyz** [comment]
Yea I could add a test for this in the next build wouldn't be too hard just need to check if it exist, then if it does lets alert the user with the option to change it/delete it

**Comment by darth62969** [comment]
i think it would be better to leave it alone, As some system admins may want to prevent you from changing the wall paper. i know if i was managing 1k systems i would want them to look alike, and since i hate the default logon BG, i would enable this option, for one it looks more professional for 2 it makes any changes you might want to make to the background not appear. .

**Comment by Toyz** [comment]
Addressed in Most recent Merge 754e12d
