### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by tig** [PFCKrutonium/Windows-10-Login-Background-Changer#76]
Installed it and selected my new photo. It said "lock to see change". I locked. I rebooted. The login screen is still boring blue. 

This is Win10 x64 upgraded over Win8.1.

**Comment by Toyz** [comment]
which version? 1.0.2.0 ot what?

**Comment by tig** [comment]
1.0.2.0.

![image](https://cloud.githubusercontent.com/assets/585482/9052804/dc6d2b9e-3a20-11e5-8008-d8299ef39ea9.png)

**Comment by Toyz** [comment]
Select your image and press "Apply Changes" your pri should change without issues

**Comment by tig** [comment]
I did that. It shows this:
![image](https://cloud.githubusercontent.com/assets/585482/9052825/1f972f6e-3a21-11e5-9e7d-d020177234e5.png)

But it lies, because the login screen is still blue.

**Comment by Toyz** [comment]
ooo do you by change have the logon image diisplay in the registry?

**Comment by tig** [comment]
yep. that fixed it. Thanks.

**Comment by Toyz** [comment]
To edit the value look at the following key:

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System]
"DisableLogonBackgroundImage"=dword:00000001

**Comment by Toyz** [comment]
Welcome, werid that the software didn't alert you that it was changed unless in that build version it doesn't exist

**Comment by Toyz** [comment]
Had image disabled in registry
