### ISSUE TITLE
Registry key disables functionality

### ISSUE THREAD

**Issue by michaelkhansen** [PFCKrutonium/Windows-10-Login-Background-Changer#82]
Hi

The programs works perfectly on my machine, expect when the registry setting "DisableLogonBackgroundimage" (dword) located in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System is set to 1 (true).

When the setting is 1, no changes are applied, so it appears the background changer is not working. 

I suggest that there is implemented a check for the registry key, and asks if that setting should be overwritten.

**Comment by Toyz** [comment]
There is a check in the newer versions but there hasn't been a release build on it yet as we're adding language support also
