### ISSUE TITLE
Settings reset after cummulative roll-up

### ISSUE THREAD

**Issue by michaelkhansen** [PFCKrutonium/Windows-10-Login-Background-Changer#99]
Hi

Not so much an issue with the Background Changer, but more an experience.

After applying the latest update (https://support.microsoft.com/en-us/kb/3081424), it does overwrite the settings and goes back to the hero image.

Regards
Michael

**Comment by darth62969** [comment]
i have had similar issues in the past on 7. Just reapply the settings and you should be fine. 

if you run into issues,  do this

> You need to select command prompt and then use 
> 
> Cd C:\Windows\SystemResources\Windows.UI.Logon
> Copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri
> 
> You may need to do this first after CD
> 
> Del Windows.UI.Logon.pri
> 
> -- Toyz

background, i have had to reset the OEMBackground setting in windows 7 repeatedly, windows kept clearing it for some reason.

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
